In [28]:
import pandas as pd
from fetch_pipeline.store_sql import get_connection
import warnings

# Suppress pandas warning about not using SQLAlchemy
warnings.filterwarnings('ignore', category=UserWarning)

In [29]:
# Connect to the MySQL database
conn = get_connection()

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

app = pd.read_sql("SELECT * FROM app", conn)

conn.close()

In [30]:
app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               400 non-null    object
 1   product_ean             400 non-null    object
 2   product_description     400 non-null    object
 3   product_image           385 non-null    object
 4   offer_ean               400 non-null    object
 5   offer_new_price         400 non-null    float64
 6   offer_original_price    400 non-null    float64
 7   offer_discount          400 non-null    float64
 8   offer_percent_discount  400 non-null    float64
 9   offer_stock_unit        400 non-null    object
 10  offer_start_time        400 non-null    datetime64[ns]
 11  offer_end_time          400 non-null    datetime64[ns]
 12  initial_stock           400 non-null    float64
 13  store_id                400 non-null    object
 14  store_name              400 non-null    object
 15  store_brand             400 non-null    object
 16  store_city              400 non-null    object
 17  store_street            400 non-null    object
 18  store_zip               400 non-null    object
 19  store_lat               400 non-null    object
 20  store_lng               400 non-null    object
 21  first_seen              400 non-null    datetime64[ns]
 22  hours_on_clearance      400 non-null    float64
 23  n_snapshots             400 non-null    float64
 24  had_overnight_gap       400 non-null    int64
 25  category_level1_en      400 non-null    object
 26  category_level2_en      400 non-null    object
 27  category_level1_da      400 non-null    object
 28  category_level2_da      400 non-null    object
 29  is_weight_based         400 non-null    int64
 30  flow_peak_hour          400 non-null    object
 31  flow_peak_value         400 non-null    float64
 32  flow_avg                400 non-null    float64
 33  flow_at_offer_start     400 non-null    float64
 34  flow_evening_share      400 non-null    float64
 35  store_open_hours        400 non-null    float64
 36  hours_until_close       400 non-null    float64
 37  is_closed_tomorrow      400 non-null    int64
 38  offer_start_dayofweek   400 non-null    object
 39  offer_start_hour_cest   400 non-null    object
 40  hours_until_offer_end   400 non-null    float64
 41  will_sell               400 non-null    int64
 42  sell_probability        400 non-null    float64
 43  predicted_at            400 non-null    datetime64[ns]
dtypes: datetime64[ns](4), float64(15), int64(4), object(21)
memory usage: 137.6+ KB

In [31]:
df = pd.read_parquet("data/dataset/labelled_offers_20260403.parquet")
df

,unique_id,store_id,store_name,store_brand,store_city,store_lat,store_lng,store_street,store_zip,product_ean,...,product_category_en,initial_stock,final_stock,first_seen,last_seen,sell_through_rate,hours_on_clearance,n_snapshots,had_overnight_gap,potential_relabelling
0,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007182_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,257470,...,Meat Fish>Lamb,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 13:15:14,0.0,18.891111,56,True,False
1,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007205_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251964,...,Meat Fish>Pork>Roasted Whole Pork Pieces>Roast...,0.097667,0.097667,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
2,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007212_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251076,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.093781,0.093781,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
3,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007229_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251072,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.092245,0.092245,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
4,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007243_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251379,...,Meat Fish>Chicken>Other Chicken>Dairy And Cold...,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712877969230,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,5.000000,5.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1228,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701205006938,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,1.000000,1.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1229,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712871634165,...,Bread And Cakes>Rye Breads>Sun Flower Seeded R...,10.000000,10.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1230,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701246266315,...,Bread And Cakes>Rye Breads>Other Rye Breads,3.000000,3.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1231,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712872146933,...,Bread And Cakes>Rye Breads>Other Rye Breads,4.000000,4.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False

In [32]:
highest_sell_thorugh = df[df['sell_through_rate'] > 0].sort_values(by='sell_through_rate', ascending=False)

highest_sell_thorugh[['store_name', 'product_description', 'offer_percent_discount']]

,store_name,product_description,offer_percent_discount
737,Netto Danmarksgd. Aalborg,MOUSSE M/ VANILJE PROTEIN LAB,33.33
715,Netto Danmarksgd. Aalborg,MEDISTER VELSMAG,40.00
292,Netto Vesterbro Aalborg,HK GRIS/KALV VELSMAG,15.00
513,Netto Vestre Allé,HYTTEOST MAMMEN,47.90
781,Netto Kollegievej,MADLAVNINGSFLØDE 15% ARLA,59.92
...,...,...,...
1083,føtex Eternitten,MESTERHAKKET KREBINET,80.00
1084,føtex Eternitten,MESTERHAKKET HAKKEBØF,80.00
1088,føtex Eternitten,LAMMECULOTTER,74.36
1087,føtex Eternitten,LAMMECULOTTE,74.36
850,føtex Aalborg,LAMMEKRONE SLAGTEREN.,61.54

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   unique_id                  1232 non-null   object
 1   store_id                   1232 non-null   object
 2   store_name                 1232 non-null   object
 3   store_brand                1232 non-null   object
 4   store_city                 1232 non-null   object
 5   store_lat                  1232 non-null   float64
 6   store_lng                  1232 non-null   float64
 7   store_street               1232 non-null   object
 8   store_zip                  1232 non-null   object
 9   product_ean                1232 non-null   object
 10  product_description        1232 non-null   object
 11  offer_ean                  1232 non-null   object
 12  offer_original_price       1232 non-null   float64
 13  offer_new_price            1232 non-null   float64
 14  offer_discount             1232 non-null   float64
 15  offer_percent_discount     1232 non-null   float64
 16  offer_stock_unit           1232 non-null   object
 17  offer_start_time           1232 non-null   datetime64[ns]
 18  offer_end_time             1232 non-null   datetime64[ns]
 19  store_customer_flow_today  1232 non-null   object
 20  product_category_da        1132 non-null   object
 21  product_category_en        1132 non-null   object
 22  initial_stock              1232 non-null   float64
 23  final_stock                1232 non-null   float64
 24  first_seen                 1232 non-null   datetime64[ns]
 25  last_seen                  1232 non-null   datetime64[ns]
 26  sell_through_rate          1232 non-null   float64
 27  hours_on_clearance         1232 non-null   float64
 28  n_snapshots                1232 non-null   int64
 29  had_overnight_gap          1232 non-null   bool
 30  potential_relabelling      1232 non-null   bool
dtypes: bool(2), datetime64[ns](4), float64(10), int64(1), object(14)
memory usage: 281.7+ KB

In [34]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005713_2...,2026-04-12 00:00:02,250587,NAKKEFILET,None,None,None,2005713,DKK,79.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.05,0.12,0.27,0.38,0.56,0.6,0.6...","0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005683_2...,2026-04-12 00:00:02,250589,NAKKEKOTELET,None,None,None,2005683,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.05,0.12,0.27,0.38,0.56,0.6,0.6...","0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,80894162,BURRATA ZANETTI,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Mozzarella,Dairy And Cold Storage>Dairy>Cheese>Mozarella,5712580560403,DKK,26.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.05,0.12,0.27,0.38,0.56,0.6,0.6...","0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-12 00:00:02,5704080955872,SPEGE. KARTOF. 3-STJERNET,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Spegepølse,Dairy And Cold Storage>Lunch Meats>Meat>Salami,5712580556215,DKK,19.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.05,0.12,0.27,0.38,0.56,0.6,0.6...","0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,5710326014302,WEINER ISKAFFE,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580562094,DKK,13.30,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.05,0.12,0.27,0.38,0.56,0.6,0.6...","0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 00:00:02,5712874624149,KYLL. TERN SALLING,https://digitalassets.sallinggroup.com/image/u...,"Mejeri & køl>Bacon, pølser & toppings>Andet to...",Dairy And Cold Storage>Bacon Sausages Toppings...,5712580601700,DKK,17.46,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00,"0,0,0,0,0,0,0.01,0.19,0.28,0.43,0.59,0.6,0.61,...","0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0...."
396,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 00:00:02,5712875087141,RØGET MØRBRAD PRINCIP,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Øvrigt pålæg,Dairy And Cold Storage>Lunch Meats>Meat>Sliced...,5712580601601,DKK,33.09,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00,"0,0,0,0,0,0,0.01,0.19,0.28,0.43,0.59,0.6,0.61,...","0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0...."
397,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 00:00:02,5712878568616,HK. GRIS/KALV 8-12% SLAGTEREN,None,Kød & fisk>Grisekød>Hakket grise- & kalvekød,Meat Fish>Pork>Minced Pork Veal,5712580603865,DKK,109.00,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00,"0,0,0,0,0,0,0.01,0.19,0.28,0.43,0.59,0.6,0.61,...","0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0...."
398,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 00:00:02,5712872136057,GULERODSBOLLER SALLING,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Lyst & groft brød>Boller,Bread And Cakes>Light Breads Dark Breads>Light...,5712580604145,DKK,15.98,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00,"0,0,0,0,0,0,0.01,0.19,0.28,0.43,0.59,0.6,0.61,...","0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0...."
399,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 00:00:02,5900244041782,HOTDOG PØLSER PØLSERIET,https://digitalassets.sallinggroup.com/image/u...,"Mejeri & køl>Bacon, pølser & toppings>Pølser>G...",Dairy And Cold Storage>Bacon Sausages Toppings...,5712580601755,DKK,20.00,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00,"0,0,0,0,0,0,0.01,0.19,0.28,0.43,0.59,0.6,0.61,...","0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0...."

In [35]:
current['store_name'].value_counts()

store_name
føtex Eternitten             83
føtex Aalborg                74
føtex Food Hasseris          53
Netto Vestre Allé            40
Netto Eternitten             37
Netto Hadsundvej Aalborg     31
Netto Vesterbro Aalborg      31
Netto Aalborg                22
Netto Kollegievej            20
Netto Danmarksgd. Aalborg     9
Name: count, dtype: int64

In [36]:
current.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     400 non-null    object
 1   fetched_at                    400 non-null    datetime64[ns]
 2   product_ean                   400 non-null    object
 3   product_description           400 non-null    object
 4   product_image                 384 non-null    object
 5   product_category_da           384 non-null    object
 6   product_category_en           384 non-null    object
 7   offer_ean                     400 non-null    object
 8   offer_currency                400 non-null    object
 9   offer_original_price          400 non-null    float64
 10  offer_new_price               400 non-null    float64
 11  offer_discount                400 non-null    float64
 12  offer_percent_discount        400 non-null    float64
 13  offer_stock                   400 non-null    float64
 14  offer_stock_unit              400 non-null    object
 15  offer_start_time              400 non-null    datetime64[ns]
 16  offer_end_time                400 non-null    datetime64[ns]
 17  offer_last_update             400 non-null    datetime64[ns]
 18  store_id                      400 non-null    object
 19  store_name                    400 non-null    object
 20  store_brand                   400 non-null    object
 21  store_lat                     400 non-null    float64
 22  store_lng                     400 non-null    float64
 23  store_street                  400 non-null    object
 24  store_city                    400 non-null    object
 25  store_zip                     400 non-null    object
 26  store_country                 400 non-null    object
 27  store_hours_today             400 non-null    object
 28  store_hours_tomorrow          400 non-null    object
 29  store_customer_flow_today     400 non-null    object
 30  store_customer_flow_tomorrow  400 non-null    object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 97.0+ KB

In [37]:
føtex_aalborg = current[current['store_name'] == 'føtex Aalborg']

føtex_aalborg[['unique_id', 'fetched_at', 'product_description', 'product_category_da', 'offer_percent_discount', 'offer_start_time', 'offer_stock_unit', 'offer_end_time', 'offer_last_update', 'offer_stock']]

,unique_id,fetched_at,product_description,product_category_da,offer_percent_discount,offer_start_time,offer_stock_unit,offer_end_time,offer_last_update,offer_stock
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005713_2...,2026-04-12 00:00:02,NAKKEFILET,None,50.00,2026-04-11 12:22:59,kg,2026-04-12 21:59:59,2026-04-11 17:13:31,0.977128
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005683_2...,2026-04-12 00:00:02,NAKKEKOTELET,None,35.00,2026-04-11 12:20:51,kg,2026-04-12 21:59:59,2026-04-11 15:28:23,0.980030
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,BURRATA ZANETTI,Mejeri & køl>Mejeri>Ost>Mozzarella,25.79,2026-04-10 05:04:27,each,2026-04-12 21:59:59,2026-04-11 15:28:23,17.000000
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-12 00:00:02,SPEGE. KARTOF. 3-STJERNET,Mejeri & køl>Pålæg>Kødpålæg>Spegepølse,49.87,2026-04-08 11:39:30,each,2026-04-14 21:59:59,2026-04-11 06:57:31,1.000000
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,WEINER ISKAFFE,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,24.81,2026-04-10 09:29:57,each,2026-04-30 21:59:59,2026-04-11 08:27:40,44.000000
...,...,...,...,...,...,...,...,...,...,...
69,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,RÖSTI STICKS CREATIVE P.,Mejeri & køl>Kartoffeltilbehør>Tilberedte kart...,23.25,2026-04-10 12:31:08,each,2026-04-16 21:59:59,2026-04-11 18:13:41,3.000000
70,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,STRACCIATELLA DANIO,Mejeri & køl>Mejeri>Yoghurt & syrnede mælkepro...,24.69,2026-04-11 03:36:05,each,2026-04-15 21:59:59,2026-04-11 18:28:48,7.000000
71,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,HVID CHEDDAR SALLING,Mejeri & køl>Mejeri>Ost>Specialost,59.93,2026-04-10 03:20:09,each,2026-04-30 21:59:59,2026-04-11 18:43:40,6.000000
72,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,KRYDDERBOLLER SALLING,Brød & kager>Lyst & groft brød>Boller,33.33,2026-04-11 16:04:04,each,2026-04-12 21:59:59,2026-04-11 18:58:41,4.000000
73,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 00:00:02,REVET MOZZARELL SALLING,Mejeri & køl>Mejeri>Ost>Revet ost & topping,24.81,2026-04-10 05:05:19,each,2026-04-16 21:59:59,2026-04-11 18:58:41,50.000000

In [38]:
føtex_aalborg['unique_id'].iloc[81]

IndexError: single positional indexer is out-of-bounds

In [ ]:
current[['unique_id', 'fetched_at', 'product_description', 'offer_stock', 'store_hours_today']]

,unique_id,fetched_at,product_description,offer_stock,store_hours_today
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005553_2...,2026-04-08 22:15:02,SLAGTERMESTEREN RIBBENSTEG,0.977902,07:00-21:00
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005515_2...,2026-04-08 22:15:02,NAKKEKOTELET,0.977128,07:00-21:00
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005539_2...,2026-04-08 22:15:02,SKANK AF GRIS,0.977128,07:00-21:00
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 22:15:02,PAN. SCHNITZLER SLAGTEREN,1.000000,07:00-21:00
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 22:15:02,BAMSEBOLLER KOHBERG,1.000000,07:00-21:00
...,...,...,...,...,...
417,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,DANBO LAGRET KLOVBORG,8.000000,07:00-21:00
418,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,GULLASH SALLING NU,1.000000,07:00-21:00
419,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,GIRASOLI PESTO PRINCIP,1.000000,07:00-21:00
420,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,KAKAOMÆLK DÅSE MATILDE,216.000000,07:00-21:00
421,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,ØKO SMØRBAR KÆRGÅRDEN,395.000000,07:00-21:00

In [ ]:
sorted_times = current['offer_start_time'].sort_values(ascending=False).unique()

sorted_times

<DatetimeArray>
['2026-04-08 18:43:31', '2026-04-08 18:43:22', '2026-04-08 18:43:08',
 '2026-04-08 18:42:51', '2026-04-08 18:42:43', '2026-04-08 18:42:26',
 '2026-04-08 18:42:12', '2026-04-08 18:41:47', '2026-04-08 17:16:01',
 '2026-04-08 17:15:56',
 ...
 '2026-04-01 03:38:31', '2026-03-31 11:22:20', '2026-03-31 10:10:00',
 '2026-03-31 09:23:01', '2026-03-30 09:57:50', '2026-03-27 08:16:41',
 '2026-03-24 07:54:05', '2026-03-24 07:06:27', '2026-03-20 09:46:10',
 '2026-03-09 16:02:46']
Length: 421, dtype: datetime64[ns]

In [ ]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005553_2...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005515_2...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005539_2...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
                             ...
417    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
418    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
419    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
420    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
421    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
Name: unique_id, Length: 422, dtype: object

In [ ]:
current['offer_stock'].value_counts()

offer_stock
1.000000      113
2.000000       66
3.000000       65
4.000000       41
5.000000       22
7.000000       16
6.000000       13
8.000000       13
11.000000       9
9.000000        7
12.000000       4
0.149035        3
10.000000       3
13.000000       2
27.000000       2
20.000000       2
18.000000       2
15.000000       2
0.977128        2
52.000000       2
22.000000       2
14.000000       2
45.000000       1
17.000000       1
0.977902        1
62.000000       1
60.000000       1
0.200371        1
86.000000       1
49.000000       1
16.000000       1
130.000000      1
68.000000       1
0.171815        1
26.000000       1
146.000000      1
80.000000       1
47.000000       1
43.000000       1
41.000000       1
114.000000      1
106.000000      1
57.000000       1
33.000000       1
44.000000       1
0.085511        1
0.113847        1
39.000000       1
74.000000       1
216.000000      1
395.000000      1
Name: count, dtype: int64

In [ ]:
# current['store_brand'] = current['store_brand'].astype('category')

In [ ]:
current.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     422 non-null    object
 1   fetched_at                    422 non-null    datetime64[ns]
 2   product_ean                   422 non-null    object
 3   product_description           422 non-null    object
 4   product_image                 395 non-null    object
 5   product_category_da           394 non-null    object
 6   product_category_en           394 non-null    object
 7   offer_ean                     422 non-null    object
 8   offer_currency                422 non-null    object
 9   offer_original_price          422 non-null    float64
 10  offer_new_price               422 non-null    float64
 11  offer_discount                422 non-null    float64
 12  offer_percent_discount        422 non-null    float64
 13  offer_stock                   422 non-null    float64
 14  offer_stock_unit              422 non-null    object
 15  offer_start_time              422 non-null    datetime64[ns]
 16  offer_end_time                422 non-null    datetime64[ns]
 17  offer_last_update             422 non-null    datetime64[ns]
 18  store_id                      422 non-null    object
 19  store_name                    422 non-null    object
 20  store_brand                   422 non-null    object
 21  store_lat                     422 non-null    float64
 22  store_lng                     422 non-null    float64
 23  store_street                  422 non-null    object
 24  store_city                    422 non-null    object
 25  store_zip                     422 non-null    object
 26  store_country                 422 non-null    object
 27  store_hours_today             422 non-null    object
 28  store_hours_tomorrow          422 non-null    object
 29  store_customer_flow_today     422 non-null    object
 30  store_customer_flow_tomorrow  422 non-null    object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 102.3+ KB

In [ ]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...,2026-04-01 18:21:46,250589,NAKKEKOTELET,None,None,None,2005225,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...,2026-04-01 18:21:46,250617,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,None,None,2005195,DKK,59.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...,2026-04-01 18:21:46,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,2005065,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...,2026-04-01 18:21:46,252962,KYLLING NUDLER GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,None,None,2005089,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005201_2...,2026-04-01 18:21:46,257809,KOTELETTER,None,None,None,2005201,DKK,65.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212026,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,5711953135095,DANBO LAGRET KLOVBORG,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Skæreost,Dairy And Cold Storage>Dairy>Cheese>Cheese For...,5712580599090,DKK,85.12,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0.01,0.11,0.23,0.3,0.46,0.61,0.53,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
212027,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,5712877218024,GULLASH SALLING NU,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,5712580596716,DKK,36.99,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0.01,0.11,0.23,0.3,0.46,0.61,0.53,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
212028,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,5712877505414,GIRASOLI PESTO PRINCIP,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Frisk pasta>Frisk pasta med fyld,Dairy And Cold Storage>Fresh Pasta>Fresh Pasta...,5712580596860,DKK,25.09,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0.01,0.11,0.23,0.3,0.46,0.61,0.53,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
212029,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,5711953161858,KAKAOMÆLK DÅSE MATILDE,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580599007,DKK,10.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0.01,0.11,0.23,0.3,0.46,0.61,0.53,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
212030,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-08 22:15:02,5760466904964,ØKO SMØRBAR KÆRGÅRDEN,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Smør & fedtstof>Smørbart,Dairy And Cold Storage>Dairy>Butter Fats>Other...,5712580599212,DKK,31.85,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0.01,0.11,0.23,0.3,0.46,0.61,0.53,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."

In [ ]:
offer_id = 'd6abf195-312b-4818-8933-bda8ecdd9fbd_5712580555560_2026-04-08 09:07:00'

offer_id_df = history[history['unique_id'] == offer_id]

offer_id_df[['unique_id', 'fetched_at', 'offer_end_time', 'product_description', 'offer_stock', 'store_hours_today', 'offer_last_update']]

,unique_id,fetched_at,offer_end_time,product_description,offer_stock,store_hours_today,offer_last_update
191723,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 11:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
192227,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 11:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
192730,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:00:03,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
193238,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
193746,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:30:03,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
194248,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
194750,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 13:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
195244,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 13:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
195731,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 13:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,20.0,07:00-21:00,2026-04-08 10:12:57
196201,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 13:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,20.0,07:00-21:00,2026-04-08 10:12:57
196671,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 14:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,20.0,07:00-21:00,2026-04-08 10:12:57
197140,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 14:15:01,2026-04-14 21:59:59,BLUE SPARK 0.75 L,20.0,07:00-21:00,2026-04-08 10:12:57
197641,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 14:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
198117,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 14:45:13,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
198595,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 15:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
199073,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 15:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
199557,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 15:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
200041,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 15:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
200519,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 16:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
200999,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 16:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,19.0,07:00-21:00,2026-04-08 12:13:16
201469,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 16:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,18.0,07:00-21:00,2026-04-08 13:43:20
201933,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 17:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,18.0,07:00-21:00,2026-04-08 13:43:20
202397,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 17:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,18.0,07:00-21:00,2026-04-08 13:43:20
202867,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 17:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,18.0,07:00-21:00,2026-04-08 13:43:20
203343,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 17:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,18.0,07:00-21:00,2026-04-08 13:43:20
203839,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 18:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
204340,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 18:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
204841,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 18:30:03,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
205331,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 18:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
205803,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 19:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
206275,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 19:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
206744,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 19:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
207216,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 19:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
207682,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 20:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
208136,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 20:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
208596,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 20:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
209055,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 20:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
209514,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 21:00:03,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
209948,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 21:15:01,2026-04-14 21:59:59,BLUE SPARK 0.75 L,16.0,07:00-21:00,2026-04-08 15:13:31
210401,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 21:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,15.0,07:00-21:00,2026-04-08 18:58:59
210834,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 21:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,15.0,07:00-21:00,2026-04-08 18:58:59
211267,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 22:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,15.0,07:00-21:00,2026-04-08 18:58:59
211690,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 22:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,15.0,07:00-21:00,2026-04-08 18:58:59

In [ ]:
history['offer_stock'].value_counts()

offer_stock
1.000000      59237
2.000000      37380
3.000000      27951
4.000000      18212
5.000000      12462
              ...
0.150731          2
0.220243          1
243.000000        1
0.989522          1
0.978088          1
Name: count, Length: 315, dtype: int64

In [ ]:
history.nunique()

unique_id                       3108
fetched_at                       517
product_ean                     1042
product_description             1059
product_image                    764
product_category_da              120
product_category_en              120
offer_ean                       3102
offer_currency                     1
offer_original_price             347
offer_new_price                  106
offer_discount                   537
offer_percent_discount           998
offer_stock                      315
offer_stock_unit                   2
offer_start_time                3094
offer_end_time                    60
offer_last_update               3962
store_id                          10
store_name                        10
store_brand                        2
store_lat                         10
store_lng                         10
store_street                      10
store_city                         1
store_zip                          1
store_country                      1
store_hours_today                  6
store_hours_tomorrow               5
store_customer_flow_today         75
store_customer_flow_tomorrow      69
dtype: int64

In [ ]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212031 entries, 0 to 212030
Data columns (total 31 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   unique_id                     212031 non-null  object
 1   fetched_at                    212031 non-null  datetime64[ns]
 2   product_ean                   212031 non-null  object
 3   product_description           212031 non-null  object
 4   product_image                 195050 non-null  object
 5   product_category_da           191279 non-null  object
 6   product_category_en           191279 non-null  object
 7   offer_ean                     212031 non-null  object
 8   offer_currency                212031 non-null  object
 9   offer_original_price          212031 non-null  float64
 10  offer_new_price               212031 non-null  float64
 11  offer_discount                212031 non-null  float64
 12  offer_percent_discount        212031 non-null  float64
 13  offer_stock                   212031 non-null  float64
 14  offer_stock_unit              212031 non-null  object
 15  offer_start_time              212031 non-null  datetime64[ns]
 16  offer_end_time                212031 non-null  datetime64[ns]
 17  offer_last_update             212031 non-null  datetime64[ns]
 18  store_id                      212031 non-null  object
 19  store_name                    212031 non-null  object
 20  store_brand                   212031 non-null  object
 21  store_lat                     212031 non-null  float64
 22  store_lng                     212031 non-null  float64
 23  store_street                  212031 non-null  object
 24  store_city                    212031 non-null  object
 25  store_zip                     212031 non-null  object
 26  store_country                 212031 non-null  object
 27  store_hours_today             212031 non-null  object
 28  store_hours_tomorrow          212031 non-null  object
 29  store_customer_flow_today     212031 non-null  object
 30  store_customer_flow_tomorrow  212031 non-null  object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 50.1+ MB

In [ ]:
history.dtypes

unique_id                               object
fetched_at                      datetime64[ns]
product_ean                             object
product_description                     object
product_image                           object
product_category_da                     object
product_category_en                     object
offer_ean                               object
offer_currency                          object
offer_original_price                   float64
offer_new_price                        float64
offer_discount                         float64
offer_percent_discount                 float64
offer_stock                            float64
offer_stock_unit                        object
offer_start_time                datetime64[ns]
offer_end_time                  datetime64[ns]
offer_last_update               datetime64[ns]
store_id                                object
store_name                              object
store_brand                             object
store_lat                              float64
store_lng                              float64
store_street                            object
store_city                              object
store_zip                               object
store_country                           object
store_hours_today                       object
store_hours_tomorrow                    object
store_customer_flow_today               object
store_customer_flow_tomorrow            object
dtype: object

In [ ]:
# Save data to a static file for testing

# history.to_csv('test_data/test_history.csv', index=False)
# current.to_csv('test_data/test_current.csv', index=False)