In [30]:
import pandas as pd
import sqlite3

In [31]:
# Connect to the database
conn = sqlite3.connect("data/food_waste.db")

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [32]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_name,store_brand,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,2026-03-28 13:50:32,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,40.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,2026-03-28 13:50:32,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,29.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,2026-03-28 13:50:32,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,44.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,2026-03-28 13:50:32,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,69.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,2026-03-28 13:50:32,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,112.75,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5712878304047,TOMAT/MOZZARELL SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580590424,DKK,25.06,16.00,9.06,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
411,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5707196210262,LEVERPOSTEJ BUDGET,https://digitalassets.sallinggroup.com/image/u...,5712580590448,DKK,14.50,11.00,3.50,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
412,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5704000502476,FRANSK POSTEJ STRYHNS,https://digitalassets.sallinggroup.com/image/u...,5712580590455,DKK,15.50,7.00,8.50,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
413,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5704000000729,FRANSK POSTEJ STRYHN'S,https://digitalassets.sallinggroup.com/image/u...,5712580590462,DKK,15.95,12.00,3.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
414,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 13:50:32,5712878117197,STENOVNS LIMPA SALLING PRIN,https://digitalassets.sallinggroup.com/image/u...,5712580589947,DKK,27.95,12.00,15.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00

In [33]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...
                             ...
410    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
411    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
412    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
413    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
414    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...
Name: unique_id, Length: 415, dtype: str

In [34]:
current.info()

<class 'pandas.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               415 non-null    str
 1   fetched_at              415 non-null    str
 2   product_ean             415 non-null    str
 3   product_description     415 non-null    str
 4   product_image           373 non-null    str
 5   offer_ean               415 non-null    str
 6   offer_currency          415 non-null    str
 7   offer_original_price    415 non-null    float64
 8   offer_new_price         415 non-null    float64
 9   offer_discount          415 non-null    float64
 10  offer_percent_discount  415 non-null    float64
 11  offer_stock             415 non-null    float64
 12  offer_stock_unit        415 non-null    str
 13  offer_start_time        415 non-null    str
 14  offer_end_time          415 non-null    str
 15  offer_last_update       415 non-null    str
 16  store_id                415 non-null    str
 17  store_name              415 non-null    str
 18  store_brand             415 non-null    str
 19  store_lat               415 non-null    float64
 20  store_lng               415 non-null    float64
 21  store_street            415 non-null    str
 22  store_city              415 non-null    str
 23  store_zip               415 non-null    str
 24  store_country           415 non-null    str
 25  store_hours_today       415 non-null    str
 26  store_hours_tomorrow    415 non-null    str
dtypes: float64(7), str(20)
memory usage: 87.7 KB

In [35]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_name,store_brand,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,2026-03-28 14:32:27,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,40.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,2026-03-28 14:32:27,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,29.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,2026-03-28 14:32:27,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,44.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,2026-03-28 14:32:27,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,69.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,2026-03-28 14:32:27,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,112.75,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5712878304047,TOMAT/MOZZARELL SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580590424,DKK,25.06,16.00,9.06,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
826,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5707196210262,LEVERPOSTEJ BUDGET,https://digitalassets.sallinggroup.com/image/u...,5712580590448,DKK,14.50,11.00,3.50,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
827,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5704000502476,FRANSK POSTEJ STRYHNS,https://digitalassets.sallinggroup.com/image/u...,5712580590455,DKK,15.50,7.00,8.50,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
828,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:50:32,5704000000729,FRANSK POSTEJ STRYHN'S,https://digitalassets.sallinggroup.com/image/u...,5712580590462,DKK,15.95,12.00,3.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
829,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 13:50:32,5712878117197,STENOVNS LIMPA SALLING PRIN,https://digitalassets.sallinggroup.com/image/u...,5712580589947,DKK,27.95,12.00,15.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00

In [36]:
history.info()

<class 'pandas.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               830 non-null    str
 1   fetched_at              830 non-null    str
 2   product_ean             830 non-null    str
 3   product_description     830 non-null    str
 4   product_image           746 non-null    str
 5   offer_ean               830 non-null    str
 6   offer_currency          830 non-null    str
 7   offer_original_price    830 non-null    float64
 8   offer_new_price         830 non-null    float64
 9   offer_discount          830 non-null    float64
 10  offer_percent_discount  830 non-null    float64
 11  offer_stock             830 non-null    float64
 12  offer_stock_unit        830 non-null    str
 13  offer_start_time        830 non-null    str
 14  offer_end_time          830 non-null    str
 15  offer_last_update       830 non-null    str
 16  store_id                830 non-null    str
 17  store_name              830 non-null    str
 18  store_brand             830 non-null    str
 19  store_lat               830 non-null    float64
 20  store_lng               830 non-null    float64
 21  store_street            830 non-null    str
 22  store_city              830 non-null    str
 23  store_zip               830 non-null    str
 24  store_country           830 non-null    str
 25  store_hours_today       830 non-null    str
 26  store_hours_tomorrow    830 non-null    str
dtypes: float64(7), str(20)
memory usage: 175.2 KB