In [ ]:
import pandas as pd
import sqlite3

In [4]:
# Connect to the database
conn = sqlite3.connect("data/food_waste.db")

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [5]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,product_category_da,product_category_en,store_customer_flow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005126_2...,2026-04-01 06:17:33,250120,SVINEMØRBRAD,https://digitalassets.sallinggroup.com/image/u...,2005126,DKK,139.00,60.0,79.00,...,Aalborg,9000,DK,07:00-21:00,closed,Kød & fisk>Grisekød>Stege & hele kødstykker>Sv...,Meat Fish>Pork>Roasted Whole Pork Pieces>Pork ...,None,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...,2026-04-01 06:17:33,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2005065,DKK,59.95,40.0,19.95,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,None,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005058_2...,2026-04-01 06:17:33,251072,MØRBRAD M KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2005058,DKK,89.95,50.0,39.95,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,None,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005072_2...,2026-04-01 06:17:33,252612,KYLLING M/ GRØNT/KAR,https://digitalassets.sallinggroup.com/image/u...,2005072,DKK,59.95,25.0,34.95,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,None,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...,2026-04-01 06:17:33,252962,KYLLING NUDLER GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2005089,DKK,59.95,35.0,24.95,...,Aalborg,9000,DK,07:00-21:00,closed,N/A,N/A,None,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 06:17:33,5712875488726,GRØN PESTO PRINCIP,https://digitalassets.sallinggroup.com/image/u...,5712580591155,DKK,26.04,16.0,10.04,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Tapas & specialiteter>Pesto & hummus,Dairy And Cold Storage>Tapas Specialities>Pest...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
640,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 06:17:33,5760466961059,CARAMEL MACCH. STARBUCKS,https://digitalassets.sallinggroup.com/image/u...,5712580592664,DKK,19.00,9.0,10.00,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
641,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-04-01 06:17:33,5707196214345,BACON 5-PAK TULIP,https://digitalassets.sallinggroup.com/image/u...,5712580589114,DKK,59.95,39.0,20.95,...,Aalborg,9000,DK,07:00-21:00,closed,"Mejeri & køl>Bacon, pølser & toppings>Bacon>Ba...",Dairy And Cold Storage>Bacon Sausages Toppings...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
642,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 06:17:33,5712875420351,MINI KYL.PØLSER SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580591247,DKK,18.77,15.0,3.77,...,Aalborg,9000,DK,07:00-21:00,closed,"Mejeri & køl>Bacon, pølser & toppings>Pølser>K...",Dairy And Cold Storage>Bacon Sausages Toppings...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
643,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258077...,2026-04-01 06:17:33,5706911030772,BACONOST TUBE NORA,https://digitalassets.sallinggroup.com/image/u...,5712580771366,DKK,14.95,10.0,4.95,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Mejeri>Ost>Smøreost,Dairy And Cold Storage>Dairy>Cheese>Cream Cheese,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."

In [6]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005126_2...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005058_2...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005072_2...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...
                             ...
639    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
640    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
641    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...
642    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
643    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258077...
Name: unique_id, Length: 644, dtype: str

In [7]:
current['offer_stock'].value_counts()

offer_stock
1.000000      178
2.000000      101
3.000000       94
4.000000       59
5.000000       46
6.000000       29
7.000000       23
8.000000       16
9.000000        9
10.000000       9
12.000000       8
14.000000       6
13.000000       5
17.000000       5
16.000000       5
0.977128        4
11.000000       4
18.000000       4
21.000000       4
22.000000       4
32.000000       4
15.000000       3
44.000000       2
42.000000       2
54.000000       2
80.000000       2
0.975392        1
100.000000      1
86.000000       1
52.000000       1
81.000000       1
101.000000      1
45.000000       1
41.000000       1
131.000000      1
149.000000      1
102.000000      1
57.000000       1
62.000000       1
67.000000       1
55.000000       1
0.093219        1
Name: count, dtype: int64

In [8]:
current.info()

<class 'pandas.DataFrame'>
RangeIndex: 644 entries, 0 to 643
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     644 non-null    str
 1   fetched_at                    644 non-null    str
 2   product_ean                   644 non-null    str
 3   product_description           644 non-null    str
 4   product_image                 598 non-null    str
 5   offer_ean                     644 non-null    str
 6   offer_currency                644 non-null    str
 7   offer_original_price          644 non-null    float64
 8   offer_new_price               644 non-null    float64
 9   offer_discount                644 non-null    float64
 10  offer_percent_discount        644 non-null    float64
 11  offer_stock                   644 non-null    float64
 12  offer_stock_unit              644 non-null    str
 13  offer_start_time              644 non-null    str
 14  offer_end_time                644 non-null    str
 15  offer_last_update             644 non-null    str
 16  store_id                      644 non-null    str
 17  store_name                    644 non-null    str
 18  store_brand                   644 non-null    str
 19  store_lat                     644 non-null    float64
 20  store_lng                     644 non-null    float64
 21  store_street                  644 non-null    str
 22  store_city                    644 non-null    str
 23  store_zip                     644 non-null    str
 24  store_country                 644 non-null    str
 25  store_hours_today             644 non-null    str
 26  store_hours_tomorrow          644 non-null    str
 27  product_category_da           644 non-null    str
 28  product_category_en           644 non-null    str
 29  store_customer_flow           0 non-null      object
 30  store_customer_flow_today     644 non-null    str
 31  store_customer_flow_tomorrow  644 non-null    str
dtypes: float64(7), object(1), str(24)
memory usage: 161.1+ KB

In [9]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,product_category_da,product_category_en,store_customer_flow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,2026-03-28 14:32:27,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,40.00,...,Aalborg,9000,DK,07:00-21:00,07:00-21:00,NaN,NaN,None,NaN,NaN
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,2026-03-28 14:32:27,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,29.95,...,Aalborg,9000,DK,07:00-21:00,07:00-21:00,NaN,NaN,None,NaN,NaN
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,2026-03-28 14:32:27,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,44.95,...,Aalborg,9000,DK,07:00-21:00,07:00-21:00,NaN,NaN,None,NaN,NaN
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,2026-03-28 14:32:27,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,69.00,...,Aalborg,9000,DK,07:00-21:00,07:00-21:00,NaN,NaN,None,NaN,NaN
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,2026-03-28 14:32:27,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,112.75,...,Aalborg,9000,DK,07:00-21:00,07:00-21:00,NaN,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123635,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 06:17:33,5712875488726,GRØN PESTO PRINCIP,https://digitalassets.sallinggroup.com/image/u...,5712580591155,DKK,26.04,16.00,10.04,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Tapas & specialiteter>Pesto & hummus,Dairy And Cold Storage>Tapas Specialities>Pest...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
123636,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 06:17:33,5760466961059,CARAMEL MACCH. STARBUCKS,https://digitalassets.sallinggroup.com/image/u...,5712580592664,DKK,19.00,9.00,10.00,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
123637,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-04-01 06:17:33,5707196214345,BACON 5-PAK TULIP,https://digitalassets.sallinggroup.com/image/u...,5712580589114,DKK,59.95,39.00,20.95,...,Aalborg,9000,DK,07:00-21:00,closed,"Mejeri & køl>Bacon, pølser & toppings>Bacon>Ba...",Dairy And Cold Storage>Bacon Sausages Toppings...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
123638,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 06:17:33,5712875420351,MINI KYL.PØLSER SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580591247,DKK,18.77,15.00,3.77,...,Aalborg,9000,DK,07:00-21:00,closed,"Mejeri & køl>Bacon, pølser & toppings>Pølser>K...",Dairy And Cold Storage>Bacon Sausages Toppings...,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
123639,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258077...,2026-04-01 06:17:33,5706911030772,BACONOST TUBE NORA,https://digitalassets.sallinggroup.com/image/u...,5712580771366,DKK,14.95,10.00,4.95,...,Aalborg,9000,DK,07:00-21:00,closed,Mejeri & køl>Mejeri>Ost>Smøreost,Dairy And Cold Storage>Dairy>Cheese>Cream Cheese,None,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."

In [10]:
history['offer_stock'].value_counts()

offer_stock
1.000000     38513
2.000000     21606
3.000000     16338
4.000000     10910
5.000000      6779
             ...
0.098575         2
71.000000        2
0.977964         2
95.000000        2
74.000000        2
Name: count, Length: 215, dtype: int64

In [11]:
history.nunique()

unique_id                       2227
fetched_at                       258
product_ean                      835
product_description              848
product_image                    611
offer_ean                       2223
offer_currency                     1
offer_original_price             304
offer_new_price                   87
offer_discount                   422
offer_percent_discount           777
offer_stock                      215
offer_stock_unit                   2
offer_start_time                2222
offer_end_time                    51
offer_last_update               2753
store_id                          10
store_name                        10
store_brand                        2
store_lat                         10
store_lng                         10
store_street                      10
store_city                         1
store_zip                          1
store_country                      1
store_hours_today                  5
store_hours_tomorrow               6
product_category_da              106
product_category_en              106
store_customer_flow                0
store_customer_flow_today         20
store_customer_flow_tomorrow      20
dtype: int64

In [12]:
history.info()

<class 'pandas.DataFrame'>
RangeIndex: 123640 entries, 0 to 123639
Data columns (total 32 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   unique_id                     123640 non-null  str
 1   fetched_at                    123640 non-null  str
 2   product_ean                   123640 non-null  str
 3   product_description           123640 non-null  str
 4   product_image                 114112 non-null  str
 5   offer_ean                     123640 non-null  str
 6   offer_currency                123640 non-null  str
 7   offer_original_price          123640 non-null  float64
 8   offer_new_price               123640 non-null  float64
 9   offer_discount                123640 non-null  float64
 10  offer_percent_discount        123640 non-null  float64
 11  offer_stock                   123640 non-null  float64
 12  offer_stock_unit              123640 non-null  str
 13  offer_start_time              123640 non-null  str
 14  offer_end_time                123640 non-null  str
 15  offer_last_update             123640 non-null  str
 16  store_id                      123640 non-null  str
 17  store_name                    123640 non-null  str
 18  store_brand                   123640 non-null  str
 19  store_lat                     123640 non-null  float64
 20  store_lng                     123640 non-null  float64
 21  store_street                  123640 non-null  str
 22  store_city                    123640 non-null  str
 23  store_zip                     123640 non-null  str
 24  store_country                 123640 non-null  str
 25  store_hours_today             123640 non-null  str
 26  store_hours_tomorrow          123640 non-null  str
 27  product_category_da           34949 non-null   str
 28  product_category_en           34949 non-null   str
 29  store_customer_flow           0 non-null       object
 30  store_customer_flow_today     33669 non-null   str
 31  store_customer_flow_tomorrow  33669 non-null   str
dtypes: float64(7), object(1), str(24)
memory usage: 30.2+ MB

In [13]:
history.dtypes

unique_id                           str
fetched_at                          str
product_ean                         str
product_description                 str
product_image                       str
offer_ean                           str
offer_currency                      str
offer_original_price            float64
offer_new_price                 float64
offer_discount                  float64
offer_percent_discount          float64
offer_stock                     float64
offer_stock_unit                    str
offer_start_time                    str
offer_end_time                      str
offer_last_update                   str
store_id                            str
store_name                          str
store_brand                         str
store_lat                       float64
store_lng                       float64
store_street                        str
store_city                          str
store_zip                           str
store_country                       str
store_hours_today                   str
store_hours_tomorrow                str
product_category_da                 str
product_category_en                 str
store_customer_flow              object
store_customer_flow_today           str
store_customer_flow_tomorrow        str
dtype: object

In [14]:
# Sort and get last snapshot per offer
history['fetched_at'] = pd.to_datetime(history['fetched_at'])
history['offer_end_time'] = pd.to_datetime(history['offer_end_time'])

last_snapshot = (
    history.sort_values('fetched_at')
    .groupby('unique_id')
    .last()
    .reset_index()
)

# How early did each offer disappear relative to its end_time?
last_snapshot['minutes_before_end'] = (
    last_snapshot['offer_end_time'] - last_snapshot['fetched_at']
).dt.total_seconds() / 60

# Distribution of this
last_snapshot['minutes_before_end'].describe()

count     2227.000000
mean      6656.762812
std      13684.488812
min        -14.000000
25%        697.633333
50%       2256.333333
75%       5027.850000
max      91228.150000
Name: minutes_before_end, dtype: float64

In [19]:
history[['offer_end_time', 'fetched_at']].head(10)

       offer_end_time          fetched_at
0 2026-03-29 21:59:59 2026-03-28 14:32:27
1 2026-03-29 21:59:59 2026-03-28 14:32:27
2 2026-03-29 21:59:59 2026-03-28 14:32:27
3 2026-03-29 21:59:59 2026-03-28 14:32:27
4 2026-04-09 21:59:59 2026-03-28 14:32:27
5 2026-04-02 21:59:59 2026-03-28 14:32:27
6 2026-04-01 21:59:59 2026-03-28 14:32:27
7 2026-04-02 21:59:59 2026-03-28 14:32:27
8 2026-03-28 22:59:59 2026-03-28 14:32:27
9 2026-04-01 21:59:59 2026-03-28 14:32:27

In [20]:
# How many snapshots does each offer have?
snapshot_counts = history.groupby('unique_id')['fetched_at'].count().rename('n_snapshots')

# How long was each offer observed (first to last snapshot)?
offer_span = history.groupby('unique_id')['fetched_at'].agg(['min', 'max'])
offer_span['observed_hours'] = (offer_span['max'] - offer_span['min']).dt.total_seconds() / 3600

# Stock trajectory — did stock drop before disappearing?
first_stock = history.sort_values('fetched_at').groupby('unique_id')['offer_stock'].first().rename('first_stock')
last_stock = history.sort_values('fetched_at').groupby('unique_id')['offer_stock'].last().rename('last_stock')

offer_summary = pd.concat([snapshot_counts, offer_span, first_stock, last_stock], axis=1)
offer_summary['stock_dropped'] = offer_summary['first_stock'] - offer_summary['last_stock']

print(offer_summary[['n_snapshots', 'observed_hours', 'first_stock', 'last_stock', 'stock_dropped']].describe())

       n_snapshots  observed_hours  first_stock   last_stock  stock_dropped
count  2227.000000     2227.000000  2227.000000  2227.000000    2227.000000
mean     55.518635       19.336469     5.149937     3.758308       1.391629
std      41.922703       16.823909    10.787727     9.345178       3.576787
min       1.000000        0.000000     0.093219     0.093219       0.000000
25%      23.000000        5.755694     1.000000     1.000000       0.000000
50%      53.000000       18.035833     3.000000     1.000000       0.000000
75%      78.000000       25.560833     5.000000     3.000000       2.000000
max     258.000000       88.450278   172.000000   149.000000      68.000000

In [21]:
print(offer_summary['last_stock'].value_counts().sort_index().head(20))

# And what share of offers had zero stock drop?
no_drop = (offer_summary['stock_dropped'] == 0).mean()
print(f"\nOffers with no stock drop: {no_drop:.1%}")

# Cross: last_stock vs whether any drop occurred
print(offer_summary.groupby('last_stock')['stock_dropped'].agg(['count', 'mean']).head(15))

last_stock
0.093219       5
0.093229       1
0.093995       1
0.095977       1
0.097683       1
0.097859       1
0.149035      14
0.149543       1
0.149577       1
0.149641       1
0.149935       1
0.150625       1
0.151073       1
0.151171       1
0.975392       1
0.977128      11
0.977336       1
0.979038       1
0.988588       1
1.000000    1081
Name: count, dtype: int64

Offers with no stock drop: 56.4%
            count      mean
last_stock
0.093219        5  0.001582
0.093229        1  0.003820
0.093995        1  0.000000
0.095977        1  0.000000
0.097683        1  0.008928
0.097859        1  0.009280
0.149035       14  0.002906
0.149543        1  0.000000
0.149577        1  0.000000
0.149641        1  0.000000
0.149935        1  0.000000
0.150625        1  0.000000
0.151073        1  0.030570
0.151171        1  0.000000
0.975392        1  0.003472

In [22]:
# For offers that DID have stock drop, what did the trajectory look like?
# Specifically - of offers ending at last_stock=1, how many had a drop vs didn't?
ended_at_1 = offer_summary[offer_summary['last_stock'] == 1.0]
print(ended_at_1['stock_dropped'].value_counts().sort_index().head(20))
print(f"\nEnded at 1 with some drop: {(ended_at_1['stock_dropped'] > 0).mean():.1%}")

stock_dropped
0.0     634
1.0     190
2.0      98
3.0      84
4.0      26
5.0      22
6.0       6
7.0       4
8.0       4
9.0       5
11.0      2
13.0      2
14.0      3
22.0      1
Name: count, dtype: int64

Ended at 1 with some drop: 41.4%

In [23]:
flat_at_1 = offer_summary[
    (offer_summary['last_stock'] == 1.0) & 
    (offer_summary['stock_dropped'] == 0.0)
]

print(flat_at_1['observed_hours'].describe())
print(f"\nObserved < 1 hour: {(flat_at_1['observed_hours'] < 1).sum()}")
print(f"Observed < 3 hours: {(flat_at_1['observed_hours'] < 3).sum()}")
print(f"Observed > 12 hours: {(flat_at_1['observed_hours'] > 12).sum()}")

count    634.000000
mean      11.148706
std        9.138348
min        0.000000
25%        2.619167
50%        8.059167
75%       20.406389
max       26.777500
Name: observed_hours, dtype: float64

Observed < 1 hour: 57
Observed < 3 hours: 184
Observed > 12 hours: 267

In [24]:
last_snapshot = history.sort_values('fetched_at').groupby('unique_id').last().reset_index()
last_snapshot['fetched_at'] = pd.to_datetime(last_snapshot['fetched_at'])
last_snapshot['offer_end_time'] = pd.to_datetime(last_snapshot['offer_end_time'])

last_snapshot['minutes_before_end'] = (
    last_snapshot['offer_end_time'] - last_snapshot['fetched_at']
).dt.total_seconds() / 60

# Bucket into same-day vs multi-day end times
last_snapshot['end_is_today'] = last_snapshot['minutes_before_end'] < 60*24

print(last_snapshot.groupby('end_is_today')['minutes_before_end'].describe())

               count         mean           std     min          25%  \
end_is_today
False         1458.0  9948.919684  15956.568051  1446.9  2380.808333
True           769.0   414.936129    395.036042   -14.0     2.400000

                      50%          75%           max
end_is_today
False         3822.433333  8142.433333  91228.150000
True           352.350000   792.866667   1430.933333

In [25]:
print(history.groupby('offer_stock_unit')['offer_stock'].describe())
print()
print(history['offer_stock_unit'].value_counts())

                     count      mean        std       min       25%       50%  \
offer_stock_unit
each              120677.0  5.814347  14.407408  1.000000  1.000000  3.000000
kg                  2963.0  0.448154   0.408721  0.093219  0.149035  0.149925

                       75%         max
offer_stock_unit
each              5.000000  172.000000
kg                0.977128    0.994318

offer_stock_unit
each    120677
kg        2963
Name: count, dtype: int64

In [26]:
last_snap_with_unit = history.sort_values('fetched_at').groupby('unique_id').last().reset_index()

ended_at_1 = last_snap_with_unit[last_snap_with_unit['offer_stock'] == 1.0]
print(ended_at_1['offer_stock_unit'].value_counts())

offer_stock_unit
each    1081
Name: count, dtype: int64

In [27]:
current_ids = set(current['unique_id'])
history_ids = set(history['unique_id'])

still_active = current_ids.intersection(history_ids)
completed = history_ids - current_ids

print(f"Still active (in current): {len(still_active)}")
print(f"Completed (not in current): {len(completed)}")

Still active (in current): 644
Completed (not in current): 1583

In [28]:
history['fetched_at'] = pd.to_datetime(history['fetched_at'])

offer_dates = history.groupby('unique_id')['fetched_at'].agg(
    first_seen=lambda x: x.min().date(),
    last_seen=lambda x: x.max().date()
)

offer_dates['spans_multiple_days'] = offer_dates['first_seen'] != offer_dates['last_seen']

print(offer_dates['spans_multiple_days'].value_counts())
print(f"\nShare spanning multiple days: {offer_dates['spans_multiple_days'].mean():.1%}")

spans_multiple_days
True     1360
False     867
Name: count, dtype: int64

Share spanning multiple days: 61.1%

In [32]:
# Pick a specific unique_id with a decent number of snapshots and some stock drop
example = offer_summary[
    (offer_summary['n_snapshots'] > 20) & 
    (offer_summary['stock_dropped'] > 0)
].index[2]

lifecycle = history[history['unique_id'] == example].sort_values('fetched_at')
print(lifecycle[['fetched_at', 'offer_stock', 'offer_stock_unit', 'offer_end_time', 'product_description']].to_string())

               fetched_at  offer_stock offer_stock_unit      offer_end_time    product_description
47406 2026-03-30 09:41:33     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
47888 2026-03-30 09:48:07     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
48382 2026-03-30 09:57:26     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
48876 2026-03-30 10:12:08     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
49398 2026-03-30 10:29:39     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
49919 2026-03-30 10:43:31     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
50440 2026-03-30 10:52:13     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
50964 2026-03-30 11:08:19     0.106611               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
51509 2026-03-30 11:28:36     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
52078 2026-03-30 11:36:59     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
52643 2026-03-30 11:50:31     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
53208 2026-03-30 12:04:16     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
53779 2026-03-30 12:15:26     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
54343 2026-03-30 12:36:46     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
54907 2026-03-30 12:46:55     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
55464 2026-03-30 13:09:51     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
56011 2026-03-30 13:31:48     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
56557 2026-03-30 13:52:46     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
57103 2026-03-30 14:06:09     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
57653 2026-03-30 14:13:47     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
58208 2026-03-30 14:32:49     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
58757 2026-03-30 14:45:58     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
59307 2026-03-30 14:53:55     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
59883 2026-03-30 15:10:38     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
60453 2026-03-30 15:37:01     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
61023 2026-03-30 15:43:41     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
61596 2026-03-30 15:54:32     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
62175 2026-03-30 16:07:38     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
62742 2026-03-30 16:26:24     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
63309 2026-03-30 16:36:45     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
63870 2026-03-30 16:50:34     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
64436 2026-03-30 17:08:25     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
65002 2026-03-30 17:22:08     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
65568 2026-03-30 17:35:01     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
66127 2026-03-30 17:46:06     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
66700 2026-03-30 18:04:59     0.104379               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
67266 2026-03-30 18:29:23     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
67829 2026-03-30 18:36:09     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
68387 2026-03-30 18:48:06     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
68945 2026-03-30 19:09:35     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
69485 2026-03-30 19:26:18     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
70025 2026-03-30 19:37:54     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
70556 2026-03-30 19:50:53     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
71087 2026-03-30 20:02:20     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
71617 2026-03-30 20:10:01     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
72144 2026-03-30 20:29:32     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
72669 2026-03-30 20:46:10     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
73188 2026-03-30 21:02:39     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
73707 2026-03-30 21:15:10     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
74224 2026-03-30 21:28:46     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
74740 2026-03-30 21:46:52     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
75256 2026-03-30 21:59:31     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
75754 2026-03-30 22:13:59     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
76203 2026-03-31 04:50:47     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
76652 2026-03-31 05:00:22     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
77102 2026-03-31 05:13:28     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
77552 2026-03-31 05:25:09     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
78002 2026-03-31 05:32:28     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
78459 2026-03-31 05:49:46     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
78916 2026-03-31 06:00:43     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
79389 2026-03-31 06:12:08     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
79862 2026-03-31 06:28:13     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
80340 2026-03-31 06:44:37     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
80818 2026-03-31 06:53:50     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
81302 2026-03-31 07:09:18     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
81812 2026-03-31 07:31:39     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
82322 2026-03-31 07:46:21     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
82834 2026-03-31 07:54:32     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
83346 2026-03-31 08:07:47     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
83879 2026-03-31 08:23:39     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
84432 2026-03-31 08:39:17     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
84985 2026-03-31 08:47:07     0.102147               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
85545 2026-03-31 09:08:41     0.099915               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
86160 2026-03-31 09:32:21     0.099915               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
86775 2026-03-31 09:40:11     0.099915               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
87391 2026-03-31 09:49:44     0.099915               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
88005 2026-03-31 10:09:48     0.099915               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
88619 2026-03-31 10:22:21     0.099915               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
89254 2026-03-31 11:04:22     0.097683               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
89894 2026-03-31 11:06:46     0.097683               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
90550 2026-03-31 11:23:20     0.097683               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
91206 2026-03-31 11:24:50     0.097683               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN
91862 2026-03-31 11:33:32     0.097683               kg 2026-03-31 21:59:59  RIBBENSSTEG SLAGTEREN

In [35]:
example_each = offer_summary[
    (offer_summary['n_snapshots'] > 20) & 
    (offer_summary['stock_dropped'] > 0)
]

# merge to get stock unit
last_snap_with_unit = history.sort_values('fetched_at').groupby('unique_id').last().reset_index()[['unique_id', 'offer_stock_unit']]
example_each = example_each.join(last_snap_with_unit.set_index('unique_id'))
example_each = example_each[example_each['offer_stock_unit'] == 'each']

example_id = example_each.index[2]
lifecycle_each = history[history['unique_id'] == example_id].sort_values('fetched_at')
print(lifecycle_each[['fetched_at', 'offer_stock', 'offer_stock_unit', 'offer_end_time', 'product_description']].to_string())

               fetched_at  offer_stock offer_stock_unit      offer_end_time        product_description
1234  2026-03-28 14:10:56          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
1635  2026-03-28 14:26:47          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
2036  2026-03-28 14:45:00          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
2437  2026-03-28 14:56:57          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
2827  2026-03-28 15:14:06          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
3220  2026-03-28 15:24:22          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
3622  2026-03-28 15:42:58          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
4024  2026-03-28 15:53:45          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
4418  2026-03-28 16:11:16          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
4805  2026-03-28 16:27:41          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
5179  2026-03-28 16:46:50          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
5565  2026-03-28 16:57:48          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
5958  2026-03-28 17:10:24          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
6347  2026-03-28 17:26:05          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
6736  2026-03-28 17:40:57          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
7119  2026-03-28 17:55:22          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
7511  2026-03-28 18:17:05          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
7903  2026-03-28 18:27:18          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
8287  2026-03-28 18:45:46          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
8667  2026-03-28 19:01:36          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
9047  2026-03-28 19:14:09          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
9417  2026-03-28 19:27:36          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
9787  2026-03-28 19:43:31          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
10157 2026-03-28 19:54:20          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
10527 2026-03-28 20:03:50          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
10894 2026-03-28 20:24:10          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
11255 2026-03-28 20:43:46          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
11616 2026-03-28 20:55:44          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
11975 2026-03-28 21:07:41          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
12326 2026-03-28 21:24:27          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
12685 2026-03-28 21:42:35          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
13044 2026-03-28 21:53:05          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
13398 2026-03-28 22:08:22          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
13701 2026-03-29 04:51:46          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
14002 2026-03-29 05:01:15          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
14303 2026-03-29 05:13:36          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
14604 2026-03-29 05:24:07          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
14913 2026-03-29 05:32:14          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
15223 2026-03-29 05:49:02          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
15533 2026-03-29 05:58:19          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
15843 2026-03-29 06:11:06          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
16154 2026-03-29 06:23:43          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
16464 2026-03-29 06:47:47          6.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
16794 2026-03-29 07:07:34          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
17115 2026-03-29 07:23:19          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
17436 2026-03-29 07:36:07          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
17769 2026-03-29 07:47:09          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
18102 2026-03-29 07:58:38          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
18433 2026-03-29 08:11:26          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
18761 2026-03-29 08:28:36          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
19086 2026-03-29 08:44:20          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
19421 2026-03-29 09:00:00          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
19756 2026-03-29 09:18:32          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
20091 2026-03-29 09:26:52          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
20437 2026-03-29 09:44:06          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
20783 2026-03-29 09:58:01          5.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
21134 2026-03-29 10:28:11          4.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
21489 2026-03-29 10:47:09          4.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
21844 2026-03-29 10:56:46          4.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
22200 2026-03-29 11:13:22          4.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
22556 2026-03-29 11:25:38          4.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
22904 2026-03-29 11:42:30          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
23253 2026-03-29 11:53:19          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
23606 2026-03-29 12:06:32          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
23980 2026-03-29 12:27:15          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
24375 2026-03-29 12:45:12          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
24771 2026-03-29 13:07:33          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
25159 2026-03-29 13:23:06          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
25564 2026-03-29 13:36:06          3.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
25992 2026-03-29 13:50:18          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
26394 2026-03-29 13:58:57          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
26799 2026-03-29 14:11:32          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
27196 2026-03-29 14:27:04          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
27581 2026-03-29 14:45:28          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
27966 2026-03-29 14:57:53          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
28342 2026-03-29 15:14:32          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
28727 2026-03-29 15:24:11          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
29092 2026-03-29 15:43:13          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
29457 2026-03-29 15:53:27          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
29806 2026-03-29 16:11:52          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
30168 2026-03-29 16:28:03          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
30527 2026-03-29 16:47:20          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
30886 2026-03-29 16:58:26          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
31247 2026-03-29 17:11:34          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
31608 2026-03-29 17:26:16          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
31989 2026-03-29 17:41:46          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
32370 2026-03-29 17:56:23          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
32769 2026-03-29 18:18:02          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
33168 2026-03-29 18:27:13          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
33565 2026-03-29 18:45:57          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
33962 2026-03-29 19:02:45          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
34359 2026-03-29 19:15:42          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
34744 2026-03-29 19:27:54          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
35128 2026-03-29 19:44:09          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
35512 2026-03-29 19:55:50          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
35896 2026-03-29 20:03:49          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
36277 2026-03-29 20:24:31          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
36656 2026-03-29 20:44:15          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
37035 2026-03-29 20:56:38          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
37414 2026-03-29 21:08:33          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
37793 2026-03-29 21:24:51          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
38170 2026-03-29 21:44:05          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
38547 2026-03-29 21:54:09          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
38921 2026-03-29 22:09:03          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
39286 2026-03-30 05:09:02          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
39651 2026-03-30 05:16:01          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
40025 2026-03-30 05:33:28          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
40399 2026-03-30 05:42:00          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
40791 2026-03-30 05:55:06          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
41183 2026-03-30 06:06:54          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
41577 2026-03-30 06:19:43          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
41972 2026-03-30 06:36:24          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
42387 2026-03-30 06:53:24          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
42802 2026-03-30 07:03:19          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
43231 2026-03-30 07:11:15          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
43685 2026-03-30 07:32:53          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
44136 2026-03-30 07:54:05          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
44588 2026-03-30 08:04:27          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
45063 2026-03-30 08:12:22          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
45538 2026-03-30 08:32:31          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
46010 2026-03-30 08:49:20          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
46482 2026-03-30 08:57:27          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
46954 2026-03-30 09:10:09          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
47426 2026-03-30 09:41:33          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
47908 2026-03-30 09:48:07          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
48402 2026-03-30 09:57:26          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
48896 2026-03-30 10:12:08          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
49416 2026-03-30 10:29:39          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
49937 2026-03-30 10:43:31          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
50458 2026-03-30 10:52:13          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
50982 2026-03-30 11:08:19          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
51527 2026-03-30 11:28:36          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
52096 2026-03-30 11:36:59          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
52661 2026-03-30 11:50:31          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
53226 2026-03-30 12:04:16          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
53795 2026-03-30 12:15:26          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
54359 2026-03-30 12:36:46          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
54923 2026-03-30 12:46:55          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
55478 2026-03-30 13:09:51          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
56025 2026-03-30 13:31:48          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
56571 2026-03-30 13:52:46          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
57117 2026-03-30 14:06:09          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
57667 2026-03-30 14:13:47          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
58217 2026-03-30 14:32:49          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
58766 2026-03-30 14:45:58          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
59316 2026-03-30 14:53:55          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
59887 2026-03-30 15:10:38          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
60457 2026-03-30 15:37:01          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS
61027 2026-03-30 15:43:41          2.0             each 2026-04-01 21:59:59  ØKO HIMMERIGET TJELE GODS

In [36]:
completed = history[~history['unique_id'].isin(current['unique_id'])]

lifecycle_stats = completed.groupby('unique_id').agg(
    first_seen=('fetched_at', 'min'),
    last_seen=('fetched_at', 'max'),
    first_stock=('offer_stock', 'first'),
    last_stock=('offer_stock', 'last'),
    n_snapshots=('fetched_at', 'count')
).reset_index()

lifecycle_stats['hours_on_clearance'] = (
    lifecycle_stats['last_seen'] - lifecycle_stats['first_seen']
).dt.total_seconds() / 3600

lifecycle_stats['sell_through_rate'] = (
    1 - (lifecycle_stats['last_stock'] / lifecycle_stats['first_stock'])
)

print(lifecycle_stats[['hours_on_clearance', 'sell_through_rate']].describe())
print(f"\nZero sell-through: {(lifecycle_stats['sell_through_rate'] == 0).mean():.1%}")
print(f"100% sell-through: {(lifecycle_stats['sell_through_rate'] == 1).mean():.1%}")

       hours_on_clearance  sell_through_rate
count         1583.000000        1583.000000
mean            18.497627           0.232267
std             15.751334           0.295969
min              0.096389           0.000000
25%              4.962083           0.000000
50%             17.225556           0.000000
75%             25.985000           0.500000
max             80.384722           0.956522

Zero sell-through: 55.1%
100% sell-through: 0.0%

In [37]:
# Is zero sell-through concentrated in specific stock units or initial stock levels?
lifecycle_stats = lifecycle_stats.merge(
    completed.groupby('unique_id')['offer_stock_unit'].first().reset_index(),
    on='unique_id'
)

print(lifecycle_stats.groupby('offer_stock_unit')['sell_through_rate'].describe())
print()
print(lifecycle_stats.groupby('offer_stock_unit')['sell_through_rate'].apply(
    lambda x: (x == 0).mean()
).rename('zero_sellthrough_rate'))

                   count      mean       std  min  25%       50%       75%  \
offer_stock_unit
each              1543.0  0.237812  0.297699  0.0  0.0  0.000000  0.500000
kg                  40.0  0.018373  0.033157  0.0  0.0  0.005791  0.024365

                       max
offer_stock_unit
each              0.956522
kg                0.168297

offer_stock_unit
each    0.554763
kg      0.400000
Name: zero_sellthrough_rate, dtype: float64

In [38]:
# Then the overnight survival check
history['fetched_at'] = pd.to_datetime(history['fetched_at'])
history['date'] = history['fetched_at'].dt.date

# Get unique dates in the data
dates = sorted(history['date'].unique())
print(f"Dates in data: {dates}")

# For each consecutive day pair, find offers alive near end of day 1
# and check if they reappear at start of day 2
results = []
for i in range(len(dates) - 1):
    day1, day2 = dates[i], dates[i+1]
    
    # Offers seen in last 2 hours of day1
    day1_data = history[history['date'] == day1]
    day1_last2h = day1_data[day1_data['fetched_at'] >= day1_data['fetched_at'].max() - pd.Timedelta(hours=2)]
    alive_eod = set(day1_last2h['unique_id'].unique())
    
    # Offers seen in first 2 hours of day2
    day2_data = history[history['date'] == day2]
    day2_first2h = day2_data[day2_data['fetched_at'] <= day2_data['fetched_at'].min() + pd.Timedelta(hours=2)]
    alive_next_morning = set(day2_first2h['unique_id'].unique())
    
    survived = alive_eod & alive_next_morning
    results.append({
        'day1': day1, 'day2': day2,
        'alive_eod': len(alive_eod),
        'survived_to_morning': len(survived),
        'survival_rate': len(survived) / len(alive_eod) if alive_eod else 0
    })

print(pd.DataFrame(results))

Dates in data: [datetime.date(2026, 3, 28), datetime.date(2026, 3, 29), datetime.date(2026, 3, 30), datetime.date(2026, 3, 31), datetime.date(2026, 4, 1)]
         day1        day2  alive_eod  survived_to_morning  survival_rate
0  2026-03-28  2026-03-29        387                  300       0.775194
1  2026-03-29  2026-03-30        381                  331       0.868766
2  2026-03-30  2026-03-31        529                  415       0.784499
3  2026-03-31  2026-04-01        641                  540       0.842434

### Building the dataset

In [41]:
import pandas as pd
import sqlite3
from pathlib import Path

conn = sqlite3.connect("data/food_waste.db")
history = pd.read_sql("SELECT * FROM history", conn)
current = pd.read_sql("SELECT * FROM current", conn)
conn.close()

# Parse timestamps
history['fetched_at'] = pd.to_datetime(history['fetched_at'])
history['offer_start_time'] = pd.to_datetime(history['offer_start_time'])
history['offer_end_time'] = pd.to_datetime(history['offer_end_time'])

# Exclude active offers
active_ids = set(current['unique_id'])
completed = history[~history['unique_id'].isin(active_ids)].copy()

print(f"Total unique offers in history: {history['unique_id'].nunique()}")
print(f"Excluded (still active): {len(active_ids)}")
print(f"Completed offers: {completed['unique_id'].nunique()}")

Total unique offers in history: 2227
Excluded (still active): 644
Completed offers: 1583

In [43]:
completed.info()

<class 'pandas.DataFrame'>
Index: 88818 entries, 0 to 120408
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     88818 non-null  str
 1   fetched_at                    88818 non-null  datetime64[us]
 2   product_ean                   88818 non-null  str
 3   product_description           88818 non-null  str
 4   product_image                 81314 non-null  str
 5   offer_ean                     88818 non-null  str
 6   offer_currency                88818 non-null  str
 7   offer_original_price          88818 non-null  float64
 8   offer_new_price               88818 non-null  float64
 9   offer_discount                88818 non-null  float64
 10  offer_percent_discount        88818 non-null  float64
 11  offer_stock                   88818 non-null  float64
 12  offer_stock_unit              88818 non-null  str
 13  offer_start_time              88818 non-null  datetime64[us]
 14  offer_end_time                88818 non-null  datetime64[us]
 15  offer_last_update             88818 non-null  str
 16  store_id                      88818 non-null  str
 17  store_name                    88818 non-null  str
 18  store_brand                   88818 non-null  str
 19  store_lat                     88818 non-null  float64
 20  store_lng                     88818 non-null  float64
 21  store_street                  88818 non-null  str
 22  store_city                    88818 non-null  str
 23  store_zip                     88818 non-null  str
 24  store_country                 88818 non-null  str
 25  store_hours_today             88818 non-null  str
 26  store_hours_tomorrow          88818 non-null  str
 27  product_category_da           10451 non-null  str
 28  product_category_en           10451 non-null  str
 29  store_customer_flow           0 non-null      object
 30  store_customer_flow_today     9719 non-null   str
 31  store_customer_flow_tomorrow  9719 non-null   str
dtypes: datetime64[us](3), float64(7), object(1), str(21)
memory usage: 22.4+ MB

In [44]:
# Sort once upfront
completed = completed.sort_values(['unique_id', 'fetched_at'])

# First and last snapshots per offer
first = completed.groupby('unique_id').first().reset_index()
last = completed.groupby('unique_id').last().reset_index()

# Overnight gap flag — any consecutive gap > 4 hours
completed['time_diff_hours'] = (
    completed.groupby('unique_id')['fetched_at']
    .diff()
    .dt.total_seconds() / 3600
)
overnight_gap = (
    completed.groupby('unique_id')['time_diff_hours']
    .max()
    .gt(4)
    .reset_index()
    .rename(columns={'time_diff_hours': 'had_overnight_gap'})
)

# Snapshot count
n_snapshots = (
    completed.groupby('unique_id')['fetched_at']
    .count()
    .reset_index()
    .rename(columns={'fetched_at': 'n_snapshots'})
)

# Build dataset from first snapshot columns
dataset = first[[
    'unique_id', 'store_id', 'store_name', 'store_brand', 'store_city',
    'product_ean', 'product_description', 'offer_ean',
    'offer_original_price', 'offer_new_price', 'offer_discount',
    'offer_percent_discount', 'offer_stock_unit', 'offer_start_time',
    'offer_end_time', 'store_customer_flow',
    'product_category_da', 'product_category_en',
]].copy()

dataset['initial_stock'] = first['offer_stock']
dataset['final_stock'] = last['offer_stock']
dataset['first_seen'] = first['fetched_at']
dataset['last_seen'] = last['fetched_at']

# Labels
dataset['sell_through_rate'] = (
    1 - (dataset['final_stock'] / dataset['initial_stock'])
).clip(0, 1)

dataset['hours_on_clearance'] = (
    dataset['last_seen'] - pd.to_datetime(dataset['offer_start_time'])
).dt.total_seconds() / 3600

# Merge metadata
dataset = dataset.merge(n_snapshots, on='unique_id')
dataset = dataset.merge(overnight_gap, on='unique_id')

print(dataset.shape)
print(dataset[['sell_through_rate', 'hours_on_clearance', 'n_snapshots', 'had_overnight_gap']].describe())

(1583, 26)
       sell_through_rate  hours_on_clearance  n_snapshots
count        1583.000000         1583.000000  1583.000000
mean            0.231846           34.881498    56.107391
std             0.295825           54.477556    41.261766
min             0.000000            0.764167     2.000000
25%             0.000000            9.696111    20.000000
50%             0.000000           25.412500    54.000000
75%             0.500000           35.813056    80.000000
max             0.956522          773.885000   250.000000

In [45]:
# Look at the extreme hours_on_clearance cases
dataset.nlargest(10, 'hours_on_clearance')[['unique_id', 'product_description', 'offer_start_time', 'first_seen', 'last_seen', 'hours_on_clearance']]

,unique_id,product_description,offer_start_time,first_seen,last_seen,hours_on_clearance
1398,d9e869ab-c63c-4218-9932-321d470b7428_571258026...,HINDBÆR DRIK VALSØLILLE,2026-02-27 12:42:08,2026-03-28 13:50:32,2026-03-31 18:35:14,773.885000
1386,d9e869ab-c63c-4218-9932-321d470b7428_2007816_2...,GRIS 9-15% HAKKEKØD,2026-03-01 08:34:43,2026-03-29 16:47:20,2026-03-29 17:56:23,681.361111
1399,d9e869ab-c63c-4218-9932-321d470b7428_571258027...,HAVREDRIK NATURLI,2026-03-03 10:52:45,2026-03-28 13:50:32,2026-03-30 13:31:48,650.650833
9,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258057...,FLÆSK I SKIVER SLAGTEREN,2026-03-07 12:11:09,2026-03-28 13:50:32,2026-03-31 22:13:37,586.041111
379,43c0c172-437a-465f-8b17-c5adf3c2b93b_571258083...,XXL SERRANO SERRANO,2026-03-11 08:10:16,2026-03-28 13:50:32,2026-03-30 08:04:27,455.903056
378,43c0c172-437a-465f-8b17-c5adf3c2b93b_571258083...,TROFIETTE CASA MILO,2026-03-11 07:46:03,2026-03-28 13:50:32,2026-03-29 17:56:23,442.172222
10,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258057...,FLÆSKEST.SAUCE JENSENS,2026-03-11 14:01:24,2026-03-28 16:46:50,2026-03-29 18:27:13,436.430278
380,43c0c172-437a-465f-8b17-c5adf3c2b93b_571258083...,TZATZIKI 200G ATHENA,2026-03-11 08:12:08,2026-03-28 13:50:32,2026-03-29 11:25:38,435.225000
381,43c0c172-437a-465f-8b17-c5adf3c2b93b_571258083...,FRANKFURTER STEFF,2026-03-13 05:55:15,2026-03-28 13:50:32,2026-03-28 22:08:22,376.218611
158,2da2b92a-25c8-48cf-a4a1-7c56b4469a02_571258015...,FL.OST PEBERROD PHILADELPHIA,2026-03-13 14:44:21,2026-03-28 13:50:32,2026-03-28 18:27:18,363.715833

In [46]:
print(dataset['had_overnight_gap'].value_counts())
print(f"With overnight gap: {dataset['had_overnight_gap'].mean():.1%}")

had_overnight_gap
True     829
False    754
Name: count, dtype: int64
With overnight gap: 52.4%

In [47]:
dataset['hours_on_clearance'] = (
    dataset['last_seen'] - dataset['first_seen']
).dt.total_seconds() / 3600

In [48]:
print(dataset['hours_on_clearance'].describe())
print(dataset.nlargest(5, 'hours_on_clearance')[['product_description', 'first_seen', 'last_seen', 'hours_on_clearance']])

count    1583.000000
mean       18.497627
std        15.751334
min         0.096389
25%         4.962083
50%        17.225556
75%        25.985000
max        80.384722
Name: hours_on_clearance, dtype: float64
          product_description          first_seen           last_seen  \
9    FLÆSK I SKIVER SLAGTEREN 2026-03-28 13:50:32 2026-03-31 22:13:37
30     ØKO LEVERPOSTEJ AALBÆK 2026-03-28 13:50:32 2026-03-31 22:13:37
243   MEXI TOPPING FALENGREEN 2026-03-28 13:50:32 2026-03-31 22:13:37
248     YMER ØKO 1KG ARLA ØKO 2026-03-28 13:50:32 2026-03-31 22:13:37
995    STJERNEHAPS 3-STJERNET 2026-03-28 13:50:32 2026-03-31 22:13:37

     hours_on_clearance
9             80.384722
30            80.384722
243           80.384722
248           80.384722
995           80.384722

In [49]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1583 entries, 0 to 1582
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               1583 non-null   str
 1   store_id                1583 non-null   str
 2   store_name              1583 non-null   str
 3   store_brand             1583 non-null   str
 4   store_city              1583 non-null   str
 5   product_ean             1583 non-null   str
 6   product_description     1583 non-null   str
 7   offer_ean               1583 non-null   str
 8   offer_original_price    1583 non-null   float64
 9   offer_new_price         1583 non-null   float64
 10  offer_discount          1583 non-null   float64
 11  offer_percent_discount  1583 non-null   float64
 12  offer_stock_unit        1583 non-null   str
 13  offer_start_time        1583 non-null   datetime64[us]
 14  offer_end_time          1583 non-null   datetime64[us]
 15  store_customer_flow     0 non-null      object
 16  product_category_da     446 non-null    str
 17  product_category_en     446 non-null    str
 18  initial_stock           1583 non-null   float64
 19  final_stock             1583 non-null   float64
 20  first_seen              1583 non-null   datetime64[us]
 21  last_seen               1583 non-null   datetime64[us]
 22  sell_through_rate       1583 non-null   float64
 23  hours_on_clearance      1583 non-null   float64
 24  n_snapshots             1583 non-null   int64
 25  had_overnight_gap       1583 non-null   bool
dtypes: bool(1), datetime64[us](4), float64(8), int64(1), object(1), str(11)
memory usage: 310.9+ KB

In [51]:
# Use product_ean instead of offer_ean
offer_timeline = dataset[['unique_id', 'store_id', 'product_ean', 'first_seen', 'last_seen', 'sell_through_rate']].copy()

merged = offer_timeline.merge(
    offer_timeline,
    on=['store_id', 'product_ean'],
    suffixes=('_prev', '_next')
)

relabelled = merged[
    (merged['unique_id_prev'] != merged['unique_id_next']) &
    (merged['first_seen_next'] > merged['last_seen_prev']) &
    (merged['first_seen_next'] - merged['last_seen_prev'] < pd.Timedelta(hours=2))
]

print(f"Potential relabelling events: {len(relabelled)}")
print(f"Unique offers potentially relabelled: {relabelled['unique_id_prev'].nunique()}")
print()
if len(relabelled) > 0:
    print(relabelled[['store_id', 'product_ean', 'last_seen_prev', 'first_seen_next', 'sell_through_rate_prev']].head(10))

Potential relabelling events: 231
Unique offers potentially relabelled: 217

                                 store_id    product_ean      last_seen_prev  \
5    1a3a385a-f1e4-4b43-bc65-aa4190a0925b         254881 2026-03-28 14:56:57
53   1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5726866108500 2026-03-28 16:27:41
80   1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5712877969230 2026-03-29 15:53:27
88   1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5701205004873 2026-03-29 15:53:27
95   1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5712878095433 2026-03-30 09:10:09
107  1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5701852263524 2026-03-30 07:32:53
123  1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5712874822156 2026-03-30 15:43:41
132  1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5701246028111 2026-03-30 10:12:08
166  1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5712874241292 2026-03-30 14:13:47
181  1a3a385a-f1e4-4b43-bc65-aa4190a0925b  5701205005467 2026-03-31 10:22:21

        first_seen_next  sell_through_rate_prev
5   2026-03-28 15:14:06                0.000000
53  2026-03-28 16:46:50                0.000000
80  2026-03-29 16:11:52                0.000000
88  2026-03-29 16:11:52                0.000000
95  2026-03-30 09:41:33                0.900000
107 2026-03-30 07:54:05                0.666667
123 2026-03-30 15:54:32                0.000000
132 2026-03-30 10:29:39                0.000000
166 2026-03-30 15:10:38                0.000000
181 2026-03-31 11:04:22                0.000000