In [37]:
import pandas as pd
import sqlite3

In [38]:
# Connect to the database
conn = sqlite3.connect("data/food_waste.db")

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [39]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_name,store_brand,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,2026-03-28 22:08:22,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,40.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,2026-03-28 22:08:22,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,29.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,2026-03-28 22:08:22,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,44.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,2026-03-28 22:08:22,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,69.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,2026-03-28 22:08:22,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,112.75,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 22:08:22,5712877994508,MUFFINS FLERKOR SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580590653,DKK,14.95,8.00,6.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
350,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 22:08:22,7311070031959,LEVAIN PÅGEN,https://digitalassets.sallinggroup.com/image/u...,5712580590660,DKK,27.95,17.00,10.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
351,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 22:08:22,5712871634165,SOLSIKKERUGBRØD SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580589930,DKK,7.95,6.00,1.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
352,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 22:08:22,5712875649059,KYLL.COCKT.PØLS SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580587936,DKK,23.03,18.00,5.03,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
353,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 22:08:22,5712878117197,STENOVNS LIMPA SALLING PRIN,https://digitalassets.sallinggroup.com/image/u...,5712580589947,DKK,27.95,12.00,15.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00

In [40]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...
                             ...
349    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
350    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
351    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...
352    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...
353    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...
Name: unique_id, Length: 354, dtype: str

In [50]:
current['offer_stock'].value_counts()

offer_stock
1.000000      123
2.000000       65
3.000000       49
4.000000       28
6.000000       18
5.000000       14
8.000000        6
7.000000        5
10.000000       5
0.977128        4
9.000000        3
20.000000       3
11.000000       3
12.000000       2
17.000000       2
0.093219        2
0.977779        1
0.149035        1
0.149641        1
0.161263        1
28.000000       1
19.000000       1
18.000000       1
16.000000       1
23.000000       1
37.000000       1
153.000000      1
114.000000      1
171.000000      1
49.000000       1
33.000000       1
141.000000      1
68.000000       1
36.000000       1
62.000000       1
0.102499        1
13.000000       1
22.000000       1
Name: count, dtype: int64

In [41]:
current.info()

<class 'pandas.DataFrame'>
RangeIndex: 354 entries, 0 to 353
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               354 non-null    str
 1   fetched_at              354 non-null    str
 2   product_ean             354 non-null    str
 3   product_description     354 non-null    str
 4   product_image           319 non-null    str
 5   offer_ean               354 non-null    str
 6   offer_currency          354 non-null    str
 7   offer_original_price    354 non-null    float64
 8   offer_new_price         354 non-null    float64
 9   offer_discount          354 non-null    float64
 10  offer_percent_discount  354 non-null    float64
 11  offer_stock             354 non-null    float64
 12  offer_stock_unit        354 non-null    str
 13  offer_start_time        354 non-null    str
 14  offer_end_time          354 non-null    str
 15  offer_last_update       354 non-null    str
 16  store_id                354 non-null    str
 17  store_name              354 non-null    str
 18  store_brand             354 non-null    str
 19  store_lat               354 non-null    float64
 20  store_lng               354 non-null    float64
 21  store_street            354 non-null    str
 22  store_city              354 non-null    str
 23  store_zip               354 non-null    str
 24  store_country           354 non-null    str
 25  store_hours_today       354 non-null    str
 26  store_hours_tomorrow    354 non-null    str
dtypes: float64(7), str(20)
memory usage: 74.8 KB

In [42]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_name,store_brand,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,2026-03-28 14:32:27,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,40.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,2026-03-28 14:32:27,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,29.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,2026-03-28 14:32:27,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,44.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,2026-03-28 14:32:27,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,69.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,2026-03-28 14:32:27,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,112.75,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13415,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 22:08:22,5712877994508,MUFFINS FLERKOR SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580590653,DKK,14.95,8.00,6.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
13416,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 22:08:22,7311070031959,LEVAIN PÅGEN,https://digitalassets.sallinggroup.com/image/u...,5712580590660,DKK,27.95,17.00,10.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
13417,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 22:08:22,5712871634165,SOLSIKKERUGBRØD SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580589930,DKK,7.95,6.00,1.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
13418,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 22:08:22,5712875649059,KYLL.COCKT.PØLS SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580587936,DKK,23.03,18.00,5.03,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
13419,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 22:08:22,5712878117197,STENOVNS LIMPA SALLING PRIN,https://digitalassets.sallinggroup.com/image/u...,5712580589947,DKK,27.95,12.00,15.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00

In [49]:
history['offer_stock'].value_counts()

offer_stock
1.000000     4540
2.000000     2455
3.000000     1863
4.000000      960
5.000000      647
             ...
0.977820        2
31.000000       2
0.181643        2
0.098575        2
71.000000       2
Name: count, Length: 80, dtype: int64

In [45]:
history.nunique()

unique_id                 584
fetched_at                 35
product_ean               384
product_description       387
product_image             281
offer_ean                 584
offer_currency              1
offer_original_price      177
offer_new_price            59
offer_discount            202
offer_percent_discount    327
offer_stock                80
offer_stock_unit            2
offer_start_time          584
offer_end_time             36
offer_last_update         574
store_id                   10
store_name                 10
store_brand                 2
store_lat                  10
store_lng                  10
store_street               10
store_city                  1
store_zip                   1
store_country               1
store_hours_today           5
store_hours_tomorrow        5
dtype: int64

In [51]:
history.info()

<class 'pandas.DataFrame'>
RangeIndex: 13420 entries, 0 to 13419
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               13420 non-null  str
 1   fetched_at              13420 non-null  str
 2   product_ean             13420 non-null  str
 3   product_description     13420 non-null  str
 4   product_image           11968 non-null  str
 5   offer_ean               13420 non-null  str
 6   offer_currency          13420 non-null  str
 7   offer_original_price    13420 non-null  float64
 8   offer_new_price         13420 non-null  float64
 9   offer_discount          13420 non-null  float64
 10  offer_percent_discount  13420 non-null  float64
 11  offer_stock             13420 non-null  float64
 12  offer_stock_unit        13420 non-null  str
 13  offer_start_time        13420 non-null  str
 14  offer_end_time          13420 non-null  str
 15  offer_last_update       13420 non-null  str
 16  store_id                13420 non-null  str
 17  store_name              13420 non-null  str
 18  store_brand             13420 non-null  str
 19  store_lat               13420 non-null  float64
 20  store_lng               13420 non-null  float64
 21  store_street            13420 non-null  str
 22  store_city              13420 non-null  str
 23  store_zip               13420 non-null  str
 24  store_country           13420 non-null  str
 25  store_hours_today       13420 non-null  str
 26  store_hours_tomorrow    13420 non-null  str
dtypes: float64(7), str(20)
memory usage: 2.8 MB

In [53]:
history.dtypes

unique_id                     str
fetched_at                    str
product_ean                   str
product_description           str
product_image                 str
offer_ean                     str
offer_currency                str
offer_original_price      float64
offer_new_price           float64
offer_discount            float64
offer_percent_discount    float64
offer_stock               float64
offer_stock_unit              str
offer_start_time              str
offer_end_time                str
offer_last_update             str
store_id                      str
store_name                    str
store_brand                   str
store_lat                 float64
store_lng                 float64
store_street                  str
store_city                    str
store_zip                     str
store_country                 str
store_hours_today             str
store_hours_tomorrow          str
dtype: object