In [23]:
import pandas as pd
from fetch_pipeline.store_sql import get_connection
import warnings

# Suppress pandas warning about not using SQLAlchemy
warnings.filterwarnings('ignore', category=UserWarning)

In [24]:
df = pd.read_parquet("data/dataset/labelled_offers_20260403.parquet")
df

,unique_id,store_id,store_name,store_brand,store_city,store_lat,store_lng,store_street,store_zip,product_ean,...,product_category_en,initial_stock,final_stock,first_seen,last_seen,sell_through_rate,hours_on_clearance,n_snapshots,had_overnight_gap,potential_relabelling
0,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007182_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,257470,...,Meat Fish>Lamb,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 13:15:14,0.0,18.891111,56,True,False
1,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007205_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251964,...,Meat Fish>Pork>Roasted Whole Pork Pieces>Roast...,0.097667,0.097667,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
2,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007212_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251076,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.093781,0.093781,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
3,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007229_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251072,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.092245,0.092245,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
4,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007243_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251379,...,Meat Fish>Chicken>Other Chicken>Dairy And Cold...,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712877969230,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,5.000000,5.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1228,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701205006938,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,1.000000,1.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1229,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712871634165,...,Bread And Cakes>Rye Breads>Sun Flower Seeded R...,10.000000,10.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1230,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701246266315,...,Bread And Cakes>Rye Breads>Other Rye Breads,3.000000,3.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1231,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712872146933,...,Bread And Cakes>Rye Breads>Other Rye Breads,4.000000,4.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False

In [25]:
highest_sell_thorugh = df[df['sell_through_rate'] > 0].sort_values(by='sell_through_rate', ascending=False)

highest_sell_thorugh[['store_name', 'product_description', 'offer_percent_discount']]

,store_name,product_description,offer_percent_discount
737,Netto Danmarksgd. Aalborg,MOUSSE M/ VANILJE PROTEIN LAB,33.33
715,Netto Danmarksgd. Aalborg,MEDISTER VELSMAG,40.00
292,Netto Vesterbro Aalborg,HK GRIS/KALV VELSMAG,15.00
513,Netto Vestre Allé,HYTTEOST MAMMEN,47.90
781,Netto Kollegievej,MADLAVNINGSFLØDE 15% ARLA,59.92
...,...,...,...
1083,føtex Eternitten,MESTERHAKKET KREBINET,80.00
1084,føtex Eternitten,MESTERHAKKET HAKKEBØF,80.00
1088,føtex Eternitten,LAMMECULOTTER,74.36
1087,føtex Eternitten,LAMMECULOTTE,74.36
850,føtex Aalborg,LAMMEKRONE SLAGTEREN.,61.54

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   unique_id                  1232 non-null   object
 1   store_id                   1232 non-null   object
 2   store_name                 1232 non-null   object
 3   store_brand                1232 non-null   object
 4   store_city                 1232 non-null   object
 5   store_lat                  1232 non-null   float64
 6   store_lng                  1232 non-null   float64
 7   store_street               1232 non-null   object
 8   store_zip                  1232 non-null   object
 9   product_ean                1232 non-null   object
 10  product_description        1232 non-null   object
 11  offer_ean                  1232 non-null   object
 12  offer_original_price       1232 non-null   float64
 13  offer_new_price            1232 non-null   float64
 14  offer_discount             1232 non-null   float64
 15  offer_percent_discount     1232 non-null   float64
 16  offer_stock_unit           1232 non-null   object
 17  offer_start_time           1232 non-null   datetime64[ns]
 18  offer_end_time             1232 non-null   datetime64[ns]
 19  store_customer_flow_today  1232 non-null   object
 20  product_category_da        1132 non-null   object
 21  product_category_en        1132 non-null   object
 22  initial_stock              1232 non-null   float64
 23  final_stock                1232 non-null   float64
 24  first_seen                 1232 non-null   datetime64[ns]
 25  last_seen                  1232 non-null   datetime64[ns]
 26  sell_through_rate          1232 non-null   float64
 27  hours_on_clearance         1232 non-null   float64
 28  n_snapshots                1232 non-null   int64
 29  had_overnight_gap          1232 non-null   bool
 30  potential_relabelling      1232 non-null   bool
dtypes: bool(2), datetime64[ns](4), float64(10), int64(1), object(14)
memory usage: 281.7+ KB

In [27]:
# Connect to the MySQL database
conn = get_connection()

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [28]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,57067636,HVIDLØGSSPEGEP 3-STJERNET,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Spegepølse,Dairy And Cold Storage>Lunch Meats>Meat>Salami,5712580550541,DKK,19.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42...","0,0,0,0,0,0,0,0.1,0.17,0.24,0.29,0.5,0.53,0.48..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,5701852264484,ØKO LETMÆLK NATURMÆLK,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Mælk>Letmælk,Dairy And Cold Storage>Dairy>Milk>Skimmed Milk,5712580550435,DKK,10.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42...","0,0,0,0,0,0,0,0.1,0.17,0.24,0.29,0.5,0.53,0.48..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,5704000502476,FRANSK POSTEJ STRYHNS,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Leverpostej & paté,Dairy And Cold Storage>Lunch Meats>Liver Paste...,5712580550510,DKK,15.50,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42...","0,0,0,0,0,0,0,0.1,0.17,0.24,0.29,0.5,0.53,0.48..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,5704080960272,OKSE. SPEGE. 3 STJERNET,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Spegepølse,Dairy And Cold Storage>Lunch Meats>Meat>Salami,5712580550534,DKK,19.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42...","0,0,0,0,0,0,0,0.1,0.17,0.24,0.29,0.5,0.53,0.48..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,5705522020295,PÅLÆGSMIX HENSYN,https://digitalassets.sallinggroup.com/image/u...,None,None,5712580550459,DKK,16.57,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42...","0,0,0,0,0,0,0,0.1,0.17,0.24,0.29,0.5,0.53,0.48..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-06 22:45:01,5706911027734,PROTEIN PITABRØ PROTEIN LAB,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Mad- & specialbrød>Pitabrød,Bread And Cakes>Bread Specialities>Pita Bread,5712580839097,DKK,25.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
189,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,5707196277562,HK. GRIS/KALV 8-12% VELSMAG,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Hakket grise- & kalvekød,Meat Fish>Pork>Minced Pork Veal,5712580841571,DKK,42.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
190,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,5711953124860,3X ESPRESSO STARBUCKS,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580841038,DKK,19.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
191,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,5711953124891,3X ESPRESSO STARBUCKS,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580841052,DKK,20.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
192,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-06 22:45:01,5724618720147,PETER LARSEN ØKO,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580837819,DKK,10.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."

In [29]:
current['store_name'].value_counts()

store_name
føtex Aalborg                58
Netto Kollegievej            33
Netto Vestre Allé            32
Netto Vesterbro Aalborg      25
Netto Aalborg                24
Netto Eternitten             13
Netto Danmarksgd. Aalborg     8
Name: count, dtype: int64

In [30]:
current[current['store_name'] == 'Netto Danmarksgd. Aalborg']

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
127,97df1790-97f6-4903-9866-6e420fb4942c_571258051...,2026-04-06 22:45:01,5701205010232,KERNEGLØD LEVEBRØD,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Rugbrød>Kernerugbrød,Bread And Cakes>Rye Breads>Seeded Rye Breads,5712580513881,DKK,13.95,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
128,97df1790-97f6-4903-9866-6e420fb4942c_571258051...,2026-04-06 22:45:01,5700426102818,TYKMÆLK 1KG KLØVER,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Yoghurt & syrnede mælkepro...,Dairy And Cold Storage>Dairy>Yoghurt Soured Mi...,5712580513232,DKK,16.95,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
129,97df1790-97f6-4903-9866-6e420fb4942c_571258077...,2026-04-06 22:45:01,5712877468016,GYROS NÆMT,None,Frost>Kød & fisk>Grisekød,Frozen Products>Frozen Meat Fish>Frozen Pork,5712580776897,DKK,39.95,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
130,97df1790-97f6-4903-9866-6e420fb4942c_571258051...,2026-04-06 22:45:01,5703603006312,GULDLEVERPØLSE LAMPE,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Kødpølse,Dairy And Cold Storage>Lunch Meats>Meat>Meat S...,5712580510545,DKK,29.95,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
131,97df1790-97f6-4903-9866-6e420fb4942c_571258051...,2026-04-06 22:45:01,5712874935726,SURDEJSBOL ØKO ØGO,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Lyst & groft brød>Toastbrød,Bread And Cakes>Light Breads Dark Breads>Toast...,5712580513829,DKK,18.99,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
132,97df1790-97f6-4903-9866-6e420fb4942c_571258050...,2026-04-06 22:45:01,5710405063818,FULDKORNSKNÆKBRØD MINIMUM,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Kiks & knækbrød>Knækbrød,Bread And Cakes>Crackers Crisp Bread>Crisp Bread,5712580508917,DKK,20.00,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
133,97df1790-97f6-4903-9866-6e420fb4942c_571258051...,2026-04-06 22:45:01,5701012523789,MØRKT RUGBRØD GAMLE MØLLE,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Rugbrød>Andre rugbrød,Bread And Cakes>Rye Breads>Other Rye Breads,5712580513843,DKK,5.75,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."
134,97df1790-97f6-4903-9866-6e420fb4942c_571258050...,2026-04-06 22:45:01,5710326021799,BUDDING KARAMEL PROTEIN LAB,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Dessert & snacks,Dairy And Cold Storage>Dairy>Desserts Snacks,5712580505848,DKK,12.00,...,57.0453,9.92405,Danmarksgade 41,Aalborg,9000,DK,07:00-23:00,07:00-23:00,"0,0,0,0,0,0,0,0.18,0.22,0.25,0.25,0.35,0.43,0....","0,0,0,0,0,0,0.01,0.21,0.22,0.23,0.26,0.39,0.43..."

In [31]:
current[['unique_id', 'fetched_at', 'product_description', 'offer_stock', 'store_hours_today']]

,unique_id,fetched_at,product_description,offer_stock,store_hours_today
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,HVIDLØGSSPEGEP 3-STJERNET,2.0,closed
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,ØKO LETMÆLK NATURMÆLK,5.0,closed
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,FRANSK POSTEJ STRYHNS,4.0,closed
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,OKSE. SPEGE. 3 STJERNET,1.0,closed
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-06 22:45:01,PÅLÆGSMIX HENSYN,1.0,closed
...,...,...,...,...,...
188,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-06 22:45:01,PROTEIN PITABRØ PROTEIN LAB,2.0,07:00-22:00
189,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,HK. GRIS/KALV 8-12% VELSMAG,8.0,07:00-22:00
190,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,3X ESPRESSO STARBUCKS,42.0,07:00-22:00
191,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,3X ESPRESSO STARBUCKS,62.0,07:00-22:00
192,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-06 22:45:01,PETER LARSEN ØKO,22.0,07:00-22:00

In [32]:
sorted_times = current['offer_start_time'].sort_values(ascending=False).unique()

sorted_times

<DatetimeArray>
['2026-04-06 17:01:03', '2026-04-06 17:00:49', '2026-04-06 17:00:42',
 '2026-04-06 16:54:22', '2026-04-06 16:52:58', '2026-04-06 16:49:45',
 '2026-04-06 16:49:16', '2026-04-06 16:47:54', '2026-04-06 16:47:22',
 '2026-04-06 16:45:54',
 ...
 '2026-04-01 04:12:47', '2026-03-31 15:27:01', '2026-03-30 09:57:34',
 '2026-03-30 06:15:39', '2026-03-26 08:32:13', '2026-03-26 08:32:00',
 '2026-03-25 13:24:26', '2026-03-24 12:32:51', '2026-03-20 09:46:10',
 '2026-03-17 11:48:50']
Length: 193, dtype: datetime64[ns]

In [33]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...
                             ...
188    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...
189    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...
190    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...
191    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...
192    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...
Name: unique_id, Length: 193, dtype: object

In [34]:
current['offer_stock'].value_counts()

offer_stock
1.0     57
2.0     30
3.0     22
5.0     15
4.0     14
8.0     10
6.0      9
7.0      6
11.0     5
13.0     4
9.0      4
10.0     3
14.0     2
18.0     2
74.0     1
17.0     1
15.0     1
47.0     1
21.0     1
27.0     1
55.0     1
42.0     1
62.0     1
22.0     1
Name: count, dtype: int64

In [35]:
# current['store_brand'] = current['store_brand'].astype('category')

In [36]:
current.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     193 non-null    object
 1   fetched_at                    193 non-null    datetime64[ns]
 2   product_ean                   193 non-null    object
 3   product_description           193 non-null    object
 4   product_image                 179 non-null    object
 5   product_category_da           179 non-null    object
 6   product_category_en           179 non-null    object
 7   offer_ean                     193 non-null    object
 8   offer_currency                193 non-null    object
 9   offer_original_price          193 non-null    float64
 10  offer_new_price               193 non-null    float64
 11  offer_discount                193 non-null    float64
 12  offer_percent_discount        193 non-null    float64
 13  offer_stock                   193 non-null    float64
 14  offer_stock_unit              193 non-null    object
 15  offer_start_time              193 non-null    datetime64[ns]
 16  offer_end_time                193 non-null    datetime64[ns]
 17  offer_last_update             193 non-null    datetime64[ns]
 18  store_id                      193 non-null    object
 19  store_name                    193 non-null    object
 20  store_brand                   193 non-null    object
 21  store_lat                     193 non-null    float64
 22  store_lng                     193 non-null    float64
 23  store_street                  193 non-null    object
 24  store_city                    193 non-null    object
 25  store_zip                     193 non-null    object
 26  store_country                 193 non-null    object
 27  store_hours_today             193 non-null    object
 28  store_hours_tomorrow          193 non-null    object
 29  store_customer_flow_today     193 non-null    object
 30  store_customer_flow_tomorrow  193 non-null    object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 46.9+ KB

In [37]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...,2026-04-01 18:21:46,250589,NAKKEKOTELET,None,None,None,2005225,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...,2026-04-01 18:21:46,250617,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,None,None,2005195,DKK,59.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...,2026-04-01 18:21:46,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,2005065,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...,2026-04-01 18:21:46,252962,KYLLING NUDLER GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,None,None,2005089,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005201_2...,2026-04-01 18:21:46,257809,KOTELETTER,None,None,None,2005201,DKK,65.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152635,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-06 22:45:01,5706911027734,PROTEIN PITABRØ PROTEIN LAB,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Mad- & specialbrød>Pitabrød,Bread And Cakes>Bread Specialities>Pita Bread,5712580839097,DKK,25.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
152636,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,5707196277562,HK. GRIS/KALV 8-12% VELSMAG,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Hakket grise- & kalvekød,Meat Fish>Pork>Minced Pork Veal,5712580841571,DKK,42.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
152637,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,5711953124860,3X ESPRESSO STARBUCKS,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580841038,DKK,19.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
152638,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258084...,2026-04-06 22:45:01,5711953124891,3X ESPRESSO STARBUCKS,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580841052,DKK,20.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."
152639,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-06 22:45:01,5724618720147,PETER LARSEN ØKO,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580837819,DKK,10.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.16,0.16,0.29,0.22,0.34,0.33,0....","0,0,0,0,0,0,0,0.17,0.23,0.3,0.28,0.43,0.39,0.4..."

In [38]:
offer_id = history['unique_id'].iloc[34]

offer_id_df = history[history['unique_id'] == offer_id]

offer_id_df[['unique_id', 'fetched_at', 'offer_end_time', 'product_description', 'offer_stock', 'store_hours_today']]

,unique_id,fetched_at,offer_end_time,product_description,offer_stock,store_hours_today
34,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:21:46,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,8.0,07:00-21:00
784,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:48:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
1505,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:49:25,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
2226,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:51:45,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
2947,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 19:00:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
...,...,...,...,...,...,...
39178,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 14:15:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
39787,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 14:30:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
40396,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 14:45:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
40974,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 15:00:18,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
41550,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 15:15:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed

In [39]:
history['offer_stock'].value_counts()

offer_stock
1.000000      41905
2.000000      27969
3.000000      20384
4.000000      12920
5.000000       8860
              ...
89.000000         2
97.000000         2
137.000000        2
111.000000        1
0.978088          1
Name: count, Length: 180, dtype: int64

In [40]:
history.nunique()

unique_id                       2297
fetched_at                       378
product_ean                      878
product_description              889
product_image                    649
product_category_da              115
product_category_en              115
offer_ean                       2294
offer_currency                     1
offer_original_price             299
offer_new_price                   95
offer_discount                   456
offer_percent_discount           836
offer_stock                      180
offer_stock_unit                   2
offer_start_time                2288
offer_end_time                    51
offer_last_update               2667
store_id                          10
store_name                        10
store_brand                        2
store_lat                         10
store_lng                         10
store_street                      10
store_city                         1
store_zip                          1
store_country                      1
store_hours_today                  6
store_hours_tomorrow               5
store_customer_flow_today         54
store_customer_flow_tomorrow      54
dtype: int64

In [41]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152640 entries, 0 to 152639
Data columns (total 31 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   unique_id                     152640 non-null  object
 1   fetched_at                    152640 non-null  datetime64[ns]
 2   product_ean                   152640 non-null  object
 3   product_description           152640 non-null  object
 4   product_image                 139682 non-null  object
 5   product_category_da           136022 non-null  object
 6   product_category_en           136022 non-null  object
 7   offer_ean                     152640 non-null  object
 8   offer_currency                152640 non-null  object
 9   offer_original_price          152640 non-null  float64
 10  offer_new_price               152640 non-null  float64
 11  offer_discount                152640 non-null  float64
 12  offer_percent_discount        152640 non-null  float64
 13  offer_stock                   152640 non-null  float64
 14  offer_stock_unit              152640 non-null  object
 15  offer_start_time              152640 non-null  datetime64[ns]
 16  offer_end_time                152640 non-null  datetime64[ns]
 17  offer_last_update             152640 non-null  datetime64[ns]
 18  store_id                      152640 non-null  object
 19  store_name                    152640 non-null  object
 20  store_brand                   152640 non-null  object
 21  store_lat                     152640 non-null  float64
 22  store_lng                     152640 non-null  float64
 23  store_street                  152640 non-null  object
 24  store_city                    152640 non-null  object
 25  store_zip                     152640 non-null  object
 26  store_country                 152640 non-null  object
 27  store_hours_today             152640 non-null  object
 28  store_hours_tomorrow          152640 non-null  object
 29  store_customer_flow_today     152640 non-null  object
 30  store_customer_flow_tomorrow  152640 non-null  object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 36.1+ MB

In [42]:
history.dtypes

unique_id                               object
fetched_at                      datetime64[ns]
product_ean                             object
product_description                     object
product_image                           object
product_category_da                     object
product_category_en                     object
offer_ean                               object
offer_currency                          object
offer_original_price                   float64
offer_new_price                        float64
offer_discount                         float64
offer_percent_discount                 float64
offer_stock                            float64
offer_stock_unit                        object
offer_start_time                datetime64[ns]
offer_end_time                  datetime64[ns]
offer_last_update               datetime64[ns]
store_id                                object
store_name                              object
store_brand                             object
store_lat                              float64
store_lng                              float64
store_street                            object
store_city                              object
store_zip                               object
store_country                           object
store_hours_today                       object
store_hours_tomorrow                    object
store_customer_flow_today               object
store_customer_flow_tomorrow            object
dtype: object

In [43]:
# Save data to a static file for testing

# history.to_csv('test_data/test_history.csv', index=False)
# current.to_csv('test_data/test_current.csv', index=False)