In [8]:
import pandas as pd
import sqlite3

In [10]:
# Connect to the database
conn = sqlite3.connect("data/food_waste.db")

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [13]:
current

,id,unique_id,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,offer_discount,...,store_name,store_brand,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow
0,1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,40.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
1,2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,29.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
2,3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,44.95,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
3,4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,69.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
4,5,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,112.75,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,418,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,5712878304047,TOMAT/MOZZARELL SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580590424,DKK,25.06,16.00,9.06,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
418,419,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,5707196210262,LEVERPOSTEJ BUDGET,https://digitalassets.sallinggroup.com/image/u...,5712580590448,DKK,14.50,11.00,3.50,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
419,420,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,5704000502476,FRANSK POSTEJ STRYHNS,https://digitalassets.sallinggroup.com/image/u...,5712580590455,DKK,15.50,7.00,8.50,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
420,421,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,5704000000729,FRANSK POSTEJ STRYHN'S,https://digitalassets.sallinggroup.com/image/u...,5712580590462,DKK,15.95,12.00,3.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
421,422,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,5712878117197,STENOVNS LIMPA SALLING PRIN,https://digitalassets.sallinggroup.com/image/u...,5712580589947,DKK,27.95,12.00,15.95,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00

In [14]:
history

,id,unique_id,fetched_at,product_ean,product_description,product_image,offer_ean,offer_currency,offer_original_price,offer_new_price,...,store_name,store_brand,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow
0,1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009896_2...,2026-03-28 13:49:13,250811,FLADE RIBBEN AF GRIS,NaN,2009896,DKK,70.00,30.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
1,2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009858_2...,2026-03-28 13:49:13,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,2009858,DKK,59.95,30.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
2,3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009865_2...,2026-03-28 13:49:13,252889,MØRBRAD M/KAR. GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,2009865,DKK,89.95,45.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
3,4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009889_2...,2026-03-28 13:49:13,254881,NAKKEFILET SLAGTEREN,https://digitalassets.sallinggroup.com/image/u...,2009889,DKK,139.00,70.00,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
4,5,d6abf195-312b-4818-8933-bda8ecdd9fbd_2009841_2...,2026-03-28 13:49:13,265048,SE PRIS PÅ VARE VESTERHAVS,https://digitalassets.sallinggroup.com/image/u...,2009841,DKK,275.00,162.25,...,føtex Aalborg,foetex,57.047333,9.924231,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,418,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:49:13,5712878304047,TOMAT/MOZZARELL SALLING,https://digitalassets.sallinggroup.com/image/u...,5712580590424,DKK,25.06,16.00,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
418,419,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:49:13,5707196210262,LEVERPOSTEJ BUDGET,https://digitalassets.sallinggroup.com/image/u...,5712580590448,DKK,14.50,11.00,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
419,420,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:49:13,5704000502476,FRANSK POSTEJ STRYHNS,https://digitalassets.sallinggroup.com/image/u...,5712580590455,DKK,15.50,7.00,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
420,421,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-03-28 13:49:13,5704000000729,FRANSK POSTEJ STRYHN'S,https://digitalassets.sallinggroup.com/image/u...,5712580590462,DKK,15.95,12.00,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00
421,422,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258058...,2026-03-28 13:49:13,5712878117197,STENOVNS LIMPA SALLING PRIN,https://digitalassets.sallinggroup.com/image/u...,5712580589947,DKK,27.95,12.00,...,føtex Food Hasseris,foetex,57.035882,9.883358,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-20:00