In [26]:
import pandas as pd
from fetch_pipeline.store_sql import get_connection
import warnings

# Suppress pandas warning about not using SQLAlchemy
warnings.filterwarnings('ignore', category=UserWarning)

In [27]:
# Connect to the MySQL database
conn = get_connection()

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

app = pd.read_sql("SELECT * FROM app", conn)

conn.close()

In [28]:
app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 46 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               377 non-null    object
 1   product_ean             377 non-null    object
 2   product_description     377 non-null    object
 3   product_image           357 non-null    object
 4   offer_ean               377 non-null    object
 5   offer_new_price         377 non-null    float64
 6   offer_original_price    377 non-null    float64
 7   offer_discount          377 non-null    float64
 8   offer_percent_discount  377 non-null    float64
 9   offer_stock_unit        377 non-null    object
 10  offer_start_time        377 non-null    datetime64[ns]
 11  offer_end_time          377 non-null    datetime64[ns]
 12  initial_stock           377 non-null    float64
 13  store_id                377 non-null    object
 14  store_name              377 non-null    object
 15  store_brand             377 non-null    object
 16  store_city              377 non-null    object
 17  store_street            377 non-null    object
 18  store_zip               377 non-null    object
 19  store_lat               377 non-null    object
 20  store_lng               377 non-null    object
 21  store_hours_today       377 non-null    object
 22  store_hours_tomorrow    377 non-null    object
 23  first_seen              377 non-null    datetime64[ns]
 24  hours_on_clearance      377 non-null    float64
 25  n_snapshots             377 non-null    float64
 26  had_overnight_gap       377 non-null    int64
 27  category_level1_en      377 non-null    object
 28  category_level2_en      377 non-null    object
 29  category_level1_da      377 non-null    object
 30  category_level2_da      377 non-null    object
 31  is_weight_based         377 non-null    int64
 32  flow_peak_hour          377 non-null    object
 33  flow_peak_value         377 non-null    float64
 34  flow_avg                377 non-null    float64
 35  flow_at_offer_start     377 non-null    float64
 36  flow_evening_share      377 non-null    float64
 37  store_open_hours        377 non-null    float64
 38  hours_until_close       377 non-null    float64
 39  is_closed_tomorrow      377 non-null    int64
 40  offer_start_dayofweek   377 non-null    object
 41  offer_start_hour_cest   377 non-null    object
 42  hours_until_offer_end   377 non-null    float64
 43  will_sell               377 non-null    int64
 44  sell_probability        377 non-null    float64
 45  predicted_at            377 non-null    datetime64[ns]
dtypes: datetime64[ns](4), float64(15), int64(4), object(23)
memory usage: 135.6+ KB

In [51]:
predictions = pd.read_parquet("data/predictions/scored_20260412_2132.parquet")
predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 49 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   unique_id               377 non-null    object
 1   product_ean             377 non-null    object
 2   product_description     377 non-null    object
 3   product_image           357 non-null    object
 4   offer_ean               377 non-null    object
 5   offer_new_price         377 non-null    float64
 6   offer_original_price    377 non-null    float64
 7   offer_discount          377 non-null    float64
 8   offer_percent_discount  377 non-null    float64
 9   offer_stock_unit        377 non-null    object
 10  offer_start_time        377 non-null    datetime64[ns]
 11  offer_end_time          377 non-null    datetime64[ns]
 12  initial_stock           377 non-null    float64
 13  store_id                377 non-null    object
 14  store_name              377 non-null    object
 15  store_brand             377 non-null    object
 16  store_city              377 non-null    object
 17  store_street            377 non-null    object
 18  store_zip               377 non-null    object
 19  store_country           377 non-null    object
 20  store_lat               377 non-null    float64
 21  store_lng               377 non-null    float64
 22  store_hours_today       377 non-null    object
 23  store_hours_tomorrow    377 non-null    object
 24  first_seen              377 non-null    datetime64[ns]
 25  last_seen               377 non-null    datetime64[ns]
 26  hours_on_clearance      377 non-null    float64
 27  n_snapshots             377 non-null    int64
 28  had_overnight_gap       377 non-null    bool
 29  potential_relabelling   377 non-null    bool
 30  category_level1_en      377 non-null    object
 31  category_level2_en      377 non-null    object
 32  category_level1_da      377 non-null    object
 33  category_level2_da      377 non-null    object
 34  is_weight_based         377 non-null    bool
 35  flow_peak_hour          377 non-null    int64
 36  flow_peak_value         377 non-null    float64
 37  flow_avg                377 non-null    float64
 38  flow_at_offer_start     377 non-null    float64
 39  flow_evening_share      377 non-null    float64
 40  store_open_hours        377 non-null    float64
 41  hours_until_close       377 non-null    float64
 42  is_closed_tomorrow      377 non-null    bool
 43  offer_start_dayofweek   377 non-null    int32
 44  offer_start_hour_cest   377 non-null    int32
 45  hours_until_offer_end   377 non-null    float64
 46  will_sell               377 non-null    int64
 47  sell_probability        377 non-null    float64
 48  predicted_at            377 non-null    object
dtypes: bool(4), datetime64[ns](4), float64(16), int32(2), int64(3), object(20)
memory usage: 131.2+ KB

In [30]:
df = pd.read_parquet("data/dataset/labelled_offers_20260403.parquet")
df

,unique_id,store_id,store_name,store_brand,store_city,store_lat,store_lng,store_street,store_zip,product_ean,...,product_category_en,initial_stock,final_stock,first_seen,last_seen,sell_through_rate,hours_on_clearance,n_snapshots,had_overnight_gap,potential_relabelling
0,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007182_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,257470,...,Meat Fish>Lamb,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 13:15:14,0.0,18.891111,56,True,False
1,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007205_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251964,...,Meat Fish>Pork>Roasted Whole Pork Pieces>Roast...,0.097667,0.097667,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
2,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007212_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251076,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.093781,0.093781,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
3,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007229_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251072,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.092245,0.092245,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
4,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007243_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251379,...,Meat Fish>Chicken>Other Chicken>Dairy And Cold...,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712877969230,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,5.000000,5.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1228,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701205006938,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,1.000000,1.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1229,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712871634165,...,Bread And Cakes>Rye Breads>Sun Flower Seeded R...,10.000000,10.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1230,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701246266315,...,Bread And Cakes>Rye Breads>Other Rye Breads,3.000000,3.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1231,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712872146933,...,Bread And Cakes>Rye Breads>Other Rye Breads,4.000000,4.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False

In [31]:
highest_sell_thorugh = df[df['sell_through_rate'] > 0].sort_values(by='sell_through_rate', ascending=False)

highest_sell_thorugh[['store_name', 'product_description', 'offer_percent_discount']]

,store_name,product_description,offer_percent_discount
737,Netto Danmarksgd. Aalborg,MOUSSE M/ VANILJE PROTEIN LAB,33.33
715,Netto Danmarksgd. Aalborg,MEDISTER VELSMAG,40.00
292,Netto Vesterbro Aalborg,HK GRIS/KALV VELSMAG,15.00
513,Netto Vestre Allé,HYTTEOST MAMMEN,47.90
781,Netto Kollegievej,MADLAVNINGSFLØDE 15% ARLA,59.92
...,...,...,...
1083,føtex Eternitten,MESTERHAKKET KREBINET,80.00
1084,føtex Eternitten,MESTERHAKKET HAKKEBØF,80.00
1088,føtex Eternitten,LAMMECULOTTER,74.36
1087,føtex Eternitten,LAMMECULOTTE,74.36
850,føtex Aalborg,LAMMEKRONE SLAGTEREN.,61.54

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   unique_id                  1232 non-null   object
 1   store_id                   1232 non-null   object
 2   store_name                 1232 non-null   object
 3   store_brand                1232 non-null   object
 4   store_city                 1232 non-null   object
 5   store_lat                  1232 non-null   float64
 6   store_lng                  1232 non-null   float64
 7   store_street               1232 non-null   object
 8   store_zip                  1232 non-null   object
 9   product_ean                1232 non-null   object
 10  product_description        1232 non-null   object
 11  offer_ean                  1232 non-null   object
 12  offer_original_price       1232 non-null   float64
 13  offer_new_price            1232 non-null   float64
 14  offer_discount             1232 non-null   float64
 15  offer_percent_discount     1232 non-null   float64
 16  offer_stock_unit           1232 non-null   object
 17  offer_start_time           1232 non-null   datetime64[ns]
 18  offer_end_time             1232 non-null   datetime64[ns]
 19  store_customer_flow_today  1232 non-null   object
 20  product_category_da        1132 non-null   object
 21  product_category_en        1132 non-null   object
 22  initial_stock              1232 non-null   float64
 23  final_stock                1232 non-null   float64
 24  first_seen                 1232 non-null   datetime64[ns]
 25  last_seen                  1232 non-null   datetime64[ns]
 26  sell_through_rate          1232 non-null   float64
 27  hours_on_clearance         1232 non-null   float64
 28  n_snapshots                1232 non-null   int64
 29  had_overnight_gap          1232 non-null   bool
 30  potential_relabelling      1232 non-null   bool
dtypes: bool(2), datetime64[ns](4), float64(10), int64(1), object(14)
memory usage: 281.7+ KB

In [33]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005713_2...,2026-04-12 21:30:03,250587,NAKKEFILET,None,None,None,2005713,DKK,79.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4...","0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005942_2...,2026-04-12 21:30:03,256098,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Andet grisekød,Meat Fish>Pork>Other Pork,2005942,DKK,70.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4...","0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,80894162,BURRATA ZANETTI,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Mozzarella,Dairy And Cold Storage>Dairy>Cheese>Mozarella,5712580560403,DKK,26.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4...","0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,5707196372410,RØ HAMBURGERRYG PÅLÆKKER,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Hamburgerryg,Dairy And Cold Storage>Lunch Meats>Meat>Smoked...,5712580565323,DKK,19.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4...","0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,5701205010232,KERNEGLØD LEVEBRØD,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Rugbrød>Kernerugbrød,Bread And Cakes>Rye Breads>Seeded Rye Breads,5712580565170,DKK,13.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,07:00-21:00,"0,0,0,0,0,0,0,0.04,0.07,0.15,0.21,0.3,0.35,0.4...","0,0,0,0,0,0,0,0.1,0.16,0.22,0.28,0.43,0.5,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,7350000553208,KEFIR MANGO ACTIVIA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Yoghurt & syrnede mælkepro...,Dairy And Cold Storage>Dairy>Yoghurt Soured Mi...,5712580601465,DKK,13.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
373,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,7350000553505,BLÅBÆR ACTIVIA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Yoghurt & syrnede mælkepro...,Dairy And Cold Storage>Dairy>Yoghurt Soured Mi...,5712580601526,DKK,13.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
374,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,7622201733681,PLANTEBASERET PHILADELPHIA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Smøreost,Dairy And Cold Storage>Dairy>Cheese>Cream Cheese,5712580600772,DKK,29.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
375,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-12 21:30:03,5711953161858,KAKAOMÆLK DÅSE MATILDE,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580599007,DKK,10.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
376,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-12 21:30:03,5712875850264,KYLLINGEPØLSER SALLING,https://digitalassets.sallinggroup.com/image/u...,"Mejeri & køl>Bacon, pølser & toppings>Pølser>K...",Dairy And Cold Storage>Bacon Sausages Toppings...,5712580598321,DKK,36.00,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."

In [34]:
current['store_name'].value_counts()

store_name
føtex Aalborg                95
føtex Eternitten             74
Netto Kollegievej            46
Netto Vestre Allé            44
føtex Food Hasseris          37
Netto Eternitten             33
Netto Vesterbro Aalborg      17
Netto Aalborg                13
Netto Hadsundvej Aalborg     12
Netto Danmarksgd. Aalborg     6
Name: count, dtype: int64

In [35]:
current.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     377 non-null    object
 1   fetched_at                    377 non-null    datetime64[ns]
 2   product_ean                   377 non-null    object
 3   product_description           377 non-null    object
 4   product_image                 357 non-null    object
 5   product_category_da           360 non-null    object
 6   product_category_en           360 non-null    object
 7   offer_ean                     377 non-null    object
 8   offer_currency                377 non-null    object
 9   offer_original_price          377 non-null    float64
 10  offer_new_price               377 non-null    float64
 11  offer_discount                377 non-null    float64
 12  offer_percent_discount        377 non-null    float64
 13  offer_stock                   377 non-null    float64
 14  offer_stock_unit              377 non-null    object
 15  offer_start_time              377 non-null    datetime64[ns]
 16  offer_end_time                377 non-null    datetime64[ns]
 17  offer_last_update             377 non-null    datetime64[ns]
 18  store_id                      377 non-null    object
 19  store_name                    377 non-null    object
 20  store_brand                   377 non-null    object
 21  store_lat                     377 non-null    float64
 22  store_lng                     377 non-null    float64
 23  store_street                  377 non-null    object
 24  store_city                    377 non-null    object
 25  store_zip                     377 non-null    object
 26  store_country                 377 non-null    object
 27  store_hours_today             377 non-null    object
 28  store_hours_tomorrow          377 non-null    object
 29  store_customer_flow_today     377 non-null    object
 30  store_customer_flow_tomorrow  377 non-null    object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 91.4+ KB

In [36]:
føtex_aalborg = current[current['store_name'] == 'føtex Aalborg']

føtex_aalborg[['unique_id', 'fetched_at', 'product_description', 'product_category_da', 'offer_percent_discount', 'offer_start_time', 'offer_stock_unit', 'offer_end_time', 'offer_last_update', 'offer_stock']]

,unique_id,fetched_at,product_description,product_category_da,offer_percent_discount,offer_start_time,offer_stock_unit,offer_end_time,offer_last_update,offer_stock
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005713_2...,2026-04-12 21:30:03,NAKKEFILET,None,50.00,2026-04-11 12:22:59,kg,2026-04-12 21:59:59,2026-04-11 17:13:31,0.977128
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005942_2...,2026-04-12 21:30:03,STEGEBEN,Kød & fisk>Grisekød>Andet grisekød,34.29,2026-04-12 12:47:08,kg,2026-04-13 21:59:59,2026-04-12 15:43:22,0.977128
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,BURRATA ZANETTI,Mejeri & køl>Mejeri>Ost>Mozzarella,25.79,2026-04-10 05:04:27,each,2026-04-12 21:59:59,2026-04-12 16:28:34,3.000000
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,RØ HAMBURGERRYG PÅLÆKKER,Mejeri & køl>Pålæg>Kødpålæg>Hamburgerryg,54.89,2026-04-12 03:15:39,each,2026-04-15 21:59:59,2026-04-12 15:58:28,6.000000
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,KERNEGLØD LEVEBRØD,Brød & kager>Rugbrød>Kernerugbrød,49.82,2026-04-11 16:07:16,each,2026-04-12 21:59:59,2026-04-11 16:08:11,1.000000
...,...,...,...,...,...,...,...,...,...,...
90,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,BAMSEBOLLER KOHBERG,Brød & kager>Lyst & groft brød>Boller,49.97,2026-04-12 15:32:57,each,2026-04-13 21:59:59,2026-04-12 17:28:36,2.000000
91,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-12 21:30:03,RAVIOLINI RICO. SALLING,Mejeri & køl>Frisk pasta>Frisk pasta med fyld,20.36,2026-04-09 06:25:30,each,2026-04-16 21:59:59,2026-04-12 17:28:36,12.000000
92,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,OSTE SNACKS HAPPY ZOO,Mejeri & køl>Mejeri>Ost>Smøreost,34.49,2026-04-12 08:30:52,each,2026-04-25 21:59:59,2026-04-12 17:28:36,3.000000
93,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,ØKO RUGBRØD M. KERNE KOHBERG,Brød & kager>Rugbrød>Kernerugbrød,59.90,2026-04-12 15:32:31,each,2026-04-13 21:59:59,2026-04-12 17:43:44,3.000000
94,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,REVET CHEDDAR SALLING,Mejeri & køl>Mejeri>Ost>Revet ost & topping,26.42,2026-04-12 04:29:50,each,2026-04-16 21:59:59,2026-04-12 17:43:44,165.000000

In [37]:
føtex_aalborg['unique_id'].iloc[81]

'd6abf195-312b-4818-8933-bda8ecdd9fbd_5712580560984_2026-04-10 07:09:28'

In [38]:
current[['unique_id', 'fetched_at', 'product_description', 'offer_stock', 'store_hours_today']]

,unique_id,fetched_at,product_description,offer_stock,store_hours_today
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005713_2...,2026-04-12 21:30:03,NAKKEFILET,0.977128,07:00-21:00
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005942_2...,2026-04-12 21:30:03,STEGEBEN,0.977128,07:00-21:00
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,BURRATA ZANETTI,3.000000,07:00-21:00
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,RØ HAMBURGERRYG PÅLÆKKER,6.000000,07:00-21:00
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...,2026-04-12 21:30:03,KERNEGLØD LEVEBRØD,1.000000,07:00-21:00
...,...,...,...,...,...
372,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,KEFIR MANGO ACTIVIA,6.000000,07:00-20:00
373,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,BLÅBÆR ACTIVIA,5.000000,07:00-20:00
374,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,PLANTEBASERET PHILADELPHIA,16.000000,07:00-20:00
375,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-12 21:30:03,KAKAOMÆLK DÅSE MATILDE,147.000000,07:00-20:00
376,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-12 21:30:03,KYLLINGEPØLSER SALLING,4.000000,07:00-20:00

In [39]:
sorted_times = current['offer_start_time'].sort_values(ascending=False).unique()

sorted_times

<DatetimeArray>
['2026-04-12 17:53:27', '2026-04-12 17:52:34', '2026-04-12 17:51:45',
 '2026-04-12 17:49:56', '2026-04-12 17:49:29', '2026-04-12 17:48:00',
 '2026-04-12 17:46:55', '2026-04-12 17:44:43', '2026-04-12 16:25:32',
 '2026-04-12 16:23:45',
 ...
 '2026-04-01 08:54:17', '2026-04-01 04:06:12', '2026-04-01 04:05:30',
 '2026-04-01 03:38:31', '2026-03-31 12:34:29', '2026-03-27 08:16:41',
 '2026-03-27 05:28:36', '2026-03-24 07:54:05', '2026-03-20 09:46:10',
 '2026-03-20 06:03:29']
Length: 377, dtype: datetime64[ns]

In [40]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005713_2...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005942_2...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258056...
                             ...
372    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...
373    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...
374    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...
375    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
376    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
Name: unique_id, Length: 377, dtype: object

In [41]:
current['offer_stock'].value_counts()

offer_stock
1.000000      112
2.000000       56
3.000000       40
4.000000       37
5.000000       20
6.000000       18
7.000000        9
14.000000       7
0.149035        6
8.000000        5
12.000000       5
13.000000       4
9.000000        3
16.000000       3
20.000000       3
42.000000       2
10.000000       2
48.000000       2
0.977128        2
11.000000       2
31.000000       2
17.000000       2
0.093219        2
81.000000       1
56.000000       1
116.000000      1
18.000000       1
103.000000      1
24.000000       1
29.000000       1
33.000000       1
52.000000       1
57.000000       1
35.000000       1
51.000000       1
0.149859        1
165.000000      1
97.000000       1
69.000000       1
326.000000      1
311.000000      1
34.000000       1
0.149683        1
0.148697        1
19.000000       1
60.000000       1
21.000000       1
38.000000       1
40.000000       1
83.000000       1
32.000000       1
84.000000       1
55.000000       1
36.000000       1
28.000000       1
147.000000      1
Name: count, dtype: int64

In [42]:
# current['store_brand'] = current['store_brand'].astype('category')

In [43]:
current.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     377 non-null    object
 1   fetched_at                    377 non-null    datetime64[ns]
 2   product_ean                   377 non-null    object
 3   product_description           377 non-null    object
 4   product_image                 357 non-null    object
 5   product_category_da           360 non-null    object
 6   product_category_en           360 non-null    object
 7   offer_ean                     377 non-null    object
 8   offer_currency                377 non-null    object
 9   offer_original_price          377 non-null    float64
 10  offer_new_price               377 non-null    float64
 11  offer_discount                377 non-null    float64
 12  offer_percent_discount        377 non-null    float64
 13  offer_stock                   377 non-null    float64
 14  offer_stock_unit              377 non-null    object
 15  offer_start_time              377 non-null    datetime64[ns]
 16  offer_end_time                377 non-null    datetime64[ns]
 17  offer_last_update             377 non-null    datetime64[ns]
 18  store_id                      377 non-null    object
 19  store_name                    377 non-null    object
 20  store_brand                   377 non-null    object
 21  store_lat                     377 non-null    float64
 22  store_lng                     377 non-null    float64
 23  store_street                  377 non-null    object
 24  store_city                    377 non-null    object
 25  store_zip                     377 non-null    object
 26  store_country                 377 non-null    object
 27  store_hours_today             377 non-null    object
 28  store_hours_tomorrow          377 non-null    object
 29  store_customer_flow_today     377 non-null    object
 30  store_customer_flow_tomorrow  377 non-null    object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 91.4+ KB

In [44]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...,2026-04-01 18:21:46,250589,NAKKEKOTELET,None,None,None,2005225,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...,2026-04-01 18:21:46,250617,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,None,None,2005195,DKK,59.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...,2026-04-01 18:21:46,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,2005065,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...,2026-04-01 18:21:46,252962,KYLLING NUDLER GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,None,None,2005089,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005201_2...,2026-04-01 18:21:46,257809,KOTELETTER,None,None,None,2005201,DKK,65.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357277,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,7350000553208,KEFIR MANGO ACTIVIA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Yoghurt & syrnede mælkepro...,Dairy And Cold Storage>Dairy>Yoghurt Soured Mi...,5712580601465,DKK,13.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
357278,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,7350000553505,BLÅBÆR ACTIVIA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Yoghurt & syrnede mælkepro...,Dairy And Cold Storage>Dairy>Yoghurt Soured Mi...,5712580601526,DKK,13.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
357279,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258060...,2026-04-12 21:30:03,7622201733681,PLANTEBASERET PHILADELPHIA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Smøreost,Dairy And Cold Storage>Dairy>Cheese>Cream Cheese,5712580600772,DKK,29.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
357280,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-12 21:30:03,5711953161858,KAKAOMÆLK DÅSE MATILDE,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580599007,DKK,10.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."
357281,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-12 21:30:03,5712875850264,KYLLINGEPØLSER SALLING,https://digitalassets.sallinggroup.com/image/u...,"Mejeri & køl>Bacon, pølser & toppings>Pølser>K...",Dairy And Cold Storage>Bacon Sausages Toppings...,5712580598321,DKK,36.00,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-20:00,07:00-21:00,"0,0,0,0,0,0,0,0.13,0.24,0.29,0.37,0.44,0.47,0....","0,0,0,0,0,0,0.01,0.1,0.2,0.34,0.38,0.54,0.47,0..."

In [45]:
offer_id = 'd6abf195-312b-4818-8933-bda8ecdd9fbd_5712580555560_2026-04-08 09:07:00'

offer_id_df = history[history['unique_id'] == offer_id]

offer_id_df[['unique_id', 'fetched_at', 'offer_end_time', 'product_description', 'offer_stock', 'store_hours_today', 'offer_last_update']]

,unique_id,fetched_at,offer_end_time,product_description,offer_stock,store_hours_today,offer_last_update
191723,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 11:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
192227,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 11:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
192730,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:00:03,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
193238,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:15:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
193746,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-08 12:30:03,2026-04-14 21:59:59,BLUE SPARK 0.75 L,22.0,07:00-21:00,2026-04-08 09:07:24
...,...,...,...,...,...,...,...
280077,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-10 16:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,2.0,07:00-21:00,2026-04-10 13:28:40
280737,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-10 16:45:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,2.0,07:00-21:00,2026-04-10 13:28:40
281397,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-10 17:00:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,2.0,07:00-21:00,2026-04-10 13:28:40
282065,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-10 17:15:07,2026-04-14 21:59:59,BLUE SPARK 0.75 L,2.0,07:00-21:00,2026-04-10 13:28:40
282725,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258055...,2026-04-10 17:30:02,2026-04-14 21:59:59,BLUE SPARK 0.75 L,2.0,07:00-21:00,2026-04-10 13:28:40

In [46]:
history['offer_stock'].value_counts()

offer_stock
1.000000      98416
2.000000      62902
3.000000      45411
4.000000      31194
5.000000      21378
              ...
0.989522          1
0.220243          1
0.978088          1
431.000000        1
0.156329          1
Name: count, Length: 463, dtype: int64

In [47]:
history.nunique()

unique_id                       4687
fetched_at                       800
product_ean                     1288
product_description             1309
product_image                    962
product_category_da              123
product_category_en              123
offer_ean                       4676
offer_currency                     1
offer_original_price             402
offer_new_price                  123
offer_discount                   657
offer_percent_discount          1249
offer_stock                      463
offer_stock_unit                   2
offer_start_time                4671
offer_end_time                    72
offer_last_update               6496
store_id                          10
store_name                        10
store_brand                        2
store_lat                         10
store_lng                         10
store_street                      10
store_city                         1
store_zip                          1
store_country                      1
store_hours_today                  6
store_hours_tomorrow               6
store_customer_flow_today        104
store_customer_flow_tomorrow      99
dtype: int64

In [48]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357282 entries, 0 to 357281
Data columns (total 31 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   unique_id                     357282 non-null  object
 1   fetched_at                    357282 non-null  datetime64[ns]
 2   product_ean                   357282 non-null  object
 3   product_description           357282 non-null  object
 4   product_image                 334003 non-null  object
 5   product_category_da           328616 non-null  object
 6   product_category_en           328616 non-null  object
 7   offer_ean                     357282 non-null  object
 8   offer_currency                357282 non-null  object
 9   offer_original_price          357282 non-null  float64
 10  offer_new_price               357282 non-null  float64
 11  offer_discount                357282 non-null  float64
 12  offer_percent_discount        357282 non-null  float64
 13  offer_stock                   357282 non-null  float64
 14  offer_stock_unit              357282 non-null  object
 15  offer_start_time              357282 non-null  datetime64[ns]
 16  offer_end_time                357282 non-null  datetime64[ns]
 17  offer_last_update             357282 non-null  datetime64[ns]
 18  store_id                      357282 non-null  object
 19  store_name                    357282 non-null  object
 20  store_brand                   357282 non-null  object
 21  store_lat                     357282 non-null  float64
 22  store_lng                     357282 non-null  float64
 23  store_street                  357282 non-null  object
 24  store_city                    357282 non-null  object
 25  store_zip                     357282 non-null  object
 26  store_country                 357282 non-null  object
 27  store_hours_today             357282 non-null  object
 28  store_hours_tomorrow          357282 non-null  object
 29  store_customer_flow_today     357282 non-null  object
 30  store_customer_flow_tomorrow  357282 non-null  object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 84.5+ MB

In [49]:
history.dtypes

unique_id                               object
fetched_at                      datetime64[ns]
product_ean                             object
product_description                     object
product_image                           object
product_category_da                     object
product_category_en                     object
offer_ean                               object
offer_currency                          object
offer_original_price                   float64
offer_new_price                        float64
offer_discount                         float64
offer_percent_discount                 float64
offer_stock                            float64
offer_stock_unit                        object
offer_start_time                datetime64[ns]
offer_end_time                  datetime64[ns]
offer_last_update               datetime64[ns]
store_id                                object
store_name                              object
store_brand                             object
store_lat                              float64
store_lng                              float64
store_street                            object
store_city                              object
store_zip                               object
store_country                           object
store_hours_today                       object
store_hours_tomorrow                    object
store_customer_flow_today               object
store_customer_flow_tomorrow            object
dtype: object

In [50]:
# Save data to a static file for testing

# history.to_csv('test_data/test_history.csv', index=False)
# current.to_csv('test_data/test_current.csv', index=False)