In [23]:
import pandas as pd
from store_sql import get_connection
import warnings

# Suppress pandas warning about not using SQLAlchemy
warnings.filterwarnings('ignore', category=UserWarning)

In [24]:
# Connect to the MySQL database
conn = get_connection()

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [25]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005287_2...,2026-04-01 19:45:01,250509,HK GRIS 3-7% MESTERHAKKET,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Hakket grisekød,Meat Fish>Pork>Minced Pork,2005287,DKK,45.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005270_2...,2026-04-01 19:45:01,250513,GRIS 9-15% HAKKEKØD,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Hakket grisekød,Meat Fish>Pork>Minced Pork,2005270,DKK,29.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...,2026-04-01 19:45:01,250589,NAKKEKOTELET,NaN,NaN,NaN,2005225,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...,2026-04-01 19:45:01,250617,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,NaN,NaN,2005195,DKK,59.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005263_2...,2026-04-01 19:45:01,251281,LAMMEKRONE SLAGTEREN.,NaN,NaN,NaN,2005263,DKK,169.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258057...,2026-04-01 19:45:01,5710326023861,MASCARPONE NORA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Mozzarella,Dairy And Cold Storage>Dairy>Cheese>Mozarella,5712580578439,DKK,22.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
709,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,5712874624149,KYLL. TERN SALLING,https://digitalassets.sallinggroup.com/image/u...,"Mejeri & køl>Bacon, pølser & toppings>Andet to...",Dairy And Cold Storage>Bacon Sausages Toppings...,5712580594002,DKK,17.46,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
710,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,5710326019376,GRÆSK FLADBRØD ATHENA,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Mad- & specialbrød>Naan- & fladbrød,Bread And Cakes>Bread Specialities>Naan Breads...,5712580595351,DKK,18.22,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
711,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,5701205005559,MULTIKER BOLLER LEVEBRØD,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Lyst & groft brød>Boller,Bread And Cakes>Light Breads Dark Breads>Light...,5712580595221,DKK,25.50,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
712,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,7311070014488,HÖNÖ BOHUSKAKA PÅGEN,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Lyst & groft brød>Boller,Bread And Cakes>Light Breads Dark Breads>Light...,5712580595283,DKK,28.15,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."

In [26]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005287_2...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005270_2...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_2005263_2...
                             ...
708    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258057...
709    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
710    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
711    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
712    1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...
Name: unique_id, Length: 713, dtype: str

In [27]:
current['offer_stock'].value_counts()

offer_stock
1.000000     212
2.000000     129
3.000000     109
4.000000      47
5.000000      39
            ...
77.000000      1
0.092245       1
0.093781       1
0.097667       1
0.094459       1
Name: count, Length: 63, dtype: int64

In [28]:
current.info()

<class 'pandas.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     713 non-null    str
 1   fetched_at                    713 non-null    datetime64[us]
 2   product_ean                   713 non-null    str
 3   product_description           713 non-null    str
 4   product_image                 654 non-null    str
 5   product_category_da           646 non-null    str
 6   product_category_en           646 non-null    str
 7   offer_ean                     713 non-null    str
 8   offer_currency                713 non-null    str
 9   offer_original_price          713 non-null    float64
 10  offer_new_price               713 non-null    float64
 11  offer_discount                713 non-null    float64
 12  offer_percent_discount        713 non-null    float64
 13  offer_stock                   713 non-null    float64
 14  offer_stock_unit              713 non-null    str
 15  offer_start_time              713 non-null    datetime64[us]
 16  offer_end_time                713 non-null    datetime64[us]
 17  offer_last_update             713 non-null    datetime64[us]
 18  store_id                      713 non-null    str
 19  store_name                    713 non-null    str
 20  store_brand                   713 non-null    str
 21  store_lat                     713 non-null    float64
 22  store_lng                     713 non-null    float64
 23  store_street                  713 non-null    str
 24  store_city                    713 non-null    str
 25  store_zip                     713 non-null    str
 26  store_country                 713 non-null    str
 27  store_hours_today             713 non-null    str
 28  store_hours_tomorrow          713 non-null    str
 29  store_customer_flow_today     713 non-null    str
 30  store_customer_flow_tomorrow  713 non-null    str
dtypes: datetime64[us](4), float64(7), str(20)
memory usage: 172.8 KB

In [29]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...,2026-04-01 18:21:46,250589,NAKKEKOTELET,NaN,NaN,NaN,2005225,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...,2026-04-01 18:21:46,250617,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,NaN,NaN,2005195,DKK,59.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...,2026-04-01 18:21:46,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,2005065,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...,2026-04-01 18:21:46,252962,KYLLING NUDLER GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,NaN,NaN,2005089,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005201_2...,2026-04-01 18:21:46,257809,KOTELETTER,NaN,NaN,NaN,2005201,DKK,65.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7866,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258057...,2026-04-01 19:45:01,5710326023861,MASCARPONE NORA,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Ost>Mozzarella,Dairy And Cold Storage>Dairy>Cheese>Mozarella,5712580578439,DKK,22.95,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
7867,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,5712874624149,KYLL. TERN SALLING,https://digitalassets.sallinggroup.com/image/u...,"Mejeri & køl>Bacon, pølser & toppings>Andet to...",Dairy And Cold Storage>Bacon Sausages Toppings...,5712580594002,DKK,17.46,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
7868,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,5710326019376,GRÆSK FLADBRØD ATHENA,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Mad- & specialbrød>Naan- & fladbrød,Bread And Cakes>Bread Specialities>Naan Breads...,5712580595351,DKK,18.22,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
7869,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,5701205005559,MULTIKER BOLLER LEVEBRØD,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Lyst & groft brød>Boller,Bread And Cakes>Light Breads Dark Breads>Light...,5712580595221,DKK,25.50,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."
7870,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_571258059...,2026-04-01 19:45:01,7311070014488,HÖNÖ BOHUSKAKA PÅGEN,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Lyst & groft brød>Boller,Bread And Cakes>Light Breads Dark Breads>Light...,5712580595283,DKK,28.15,...,57.0359,9.88336,Hasseris Bymidte 29,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0.01,0.1,0.21,0.26,0.35,0.52,0.43,...","0,0,0,0,0.01,0,0.01,0.14,0.2,0.34,0.39,0.54,0...."

In [30]:
history['offer_stock'].value_counts()

offer_stock
1.0     2355
2.0     1377
3.0     1175
4.0      512
5.0      489
        ...
52.0       1
91.0       1
56.0       1
79.0       1
96.0       1
Name: count, Length: 74, dtype: int64

In [31]:
history.nunique()

unique_id                       787
fetched_at                       11
product_ean                     506
product_description             506
product_image                   368
product_category_da             100
product_category_en             100
offer_ean                       787
offer_currency                    1
offer_original_price            222
offer_new_price                  63
offer_discount                  275
offer_percent_discount          447
offer_stock                      74
offer_stock_unit                  2
offer_start_time                786
offer_end_time                   39
offer_last_update               568
store_id                         10
store_name                       10
store_brand                       2
store_lat                        10
store_lng                        10
store_street                     10
store_city                        1
store_zip                         1
store_country                     1
store_hours_today                 4
store_hours_tomorrow              3
store_customer_flow_today        10
store_customer_flow_tomorrow     10
dtype: int64

In [32]:
history.info()

<class 'pandas.DataFrame'>
RangeIndex: 7871 entries, 0 to 7870
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     7871 non-null   str
 1   fetched_at                    7871 non-null   datetime64[us]
 2   product_ean                   7871 non-null   str
 3   product_description           7871 non-null   str
 4   product_image                 7214 non-null   str
 5   product_category_da           7118 non-null   str
 6   product_category_en           7118 non-null   str
 7   offer_ean                     7871 non-null   str
 8   offer_currency                7871 non-null   str
 9   offer_original_price          7871 non-null   float64
 10  offer_new_price               7871 non-null   float64
 11  offer_discount                7871 non-null   float64
 12  offer_percent_discount        7871 non-null   float64
 13  offer_stock                   7871 non-null   float64
 14  offer_stock_unit              7871 non-null   str
 15  offer_start_time              7871 non-null   datetime64[us]
 16  offer_end_time                7871 non-null   datetime64[us]
 17  offer_last_update             7871 non-null   datetime64[us]
 18  store_id                      7871 non-null   str
 19  store_name                    7871 non-null   str
 20  store_brand                   7871 non-null   str
 21  store_lat                     7871 non-null   float64
 22  store_lng                     7871 non-null   float64
 23  store_street                  7871 non-null   str
 24  store_city                    7871 non-null   str
 25  store_zip                     7871 non-null   str
 26  store_country                 7871 non-null   str
 27  store_hours_today             7871 non-null   str
 28  store_hours_tomorrow          7871 non-null   str
 29  store_customer_flow_today     7871 non-null   str
 30  store_customer_flow_tomorrow  7871 non-null   str
dtypes: datetime64[us](4), float64(7), str(20)
memory usage: 1.9 MB

In [33]:
history.dtypes

unique_id                                  str
fetched_at                      datetime64[us]
product_ean                                str
product_description                        str
product_image                              str
product_category_da                        str
product_category_en                        str
offer_ean                                  str
offer_currency                             str
offer_original_price                   float64
offer_new_price                        float64
offer_discount                         float64
offer_percent_discount                 float64
offer_stock                            float64
offer_stock_unit                           str
offer_start_time                datetime64[us]
offer_end_time                  datetime64[us]
offer_last_update               datetime64[us]
store_id                                   str
store_name                                 str
store_brand                                str
store_lat                              float64
store_lng                              float64
store_street                               str
store_city                                 str
store_zip                                  str
store_country                              str
store_hours_today                          str
store_hours_tomorrow                       str
store_customer_flow_today                  str
store_customer_flow_tomorrow               str
dtype: object

In [ ]:
# Save data to a static file for testing

history.to_csv('test_data/test_history.csv', index=False)
current.to_csv('test_data/test_current.csv', index=False)