In [1]:
import pandas as pd
from store_sql import get_connection
import warnings

# Suppress pandas warning about not using SQLAlchemy
warnings.filterwarnings('ignore', category=UserWarning)

ModuleNotFoundError: No module named 'store_sql'

In [ ]:
df = pd.read_parquet("data/dataset/labelled_offers_20260403.parquet")
df

,unique_id,store_id,store_name,store_brand,store_city,store_lat,store_lng,store_street,store_zip,product_ean,...,product_category_en,initial_stock,final_stock,first_seen,last_seen,sell_through_rate,hours_on_clearance,n_snapshots,had_overnight_gap,potential_relabelling
0,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007182_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,257470,...,Meat Fish>Lamb,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 13:15:14,0.0,18.891111,56,True,False
1,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007205_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251964,...,Meat Fish>Pork>Roasted Whole Pork Pieces>Roast...,0.097667,0.097667,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
2,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007212_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251076,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.093781,0.093781,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
3,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007229_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251072,...,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,0.092245,0.092245,2026-04-01 18:21:46,2026-04-02 20:15:02,0.0,25.887778,82,True,False
4,1a3a385a-f1e4-4b43-bc65-aa4190a0925b_2007243_2...,1a3a385a-f1e4-4b43-bc65-aa4190a0925b,føtex Food Hasseris,foetex,Aalborg,57.0359,9.88336,Hasseris Bymidte 29,9000,251379,...,Meat Fish>Chicken>Other Chicken>Dairy And Cold...,0.093219,0.093219,2026-04-01 18:21:46,2026-04-02 14:30:02,0.0,20.137778,61,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1174,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712877969230,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,5.000000,5.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1175,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701205006938,...,Bread And Cakes>Rye Breads>Seeded Rye Breads,1.000000,1.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1176,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712871634165,...,Bread And Cakes>Rye Breads>Sun Flower Seeded R...,10.000000,10.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1177,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5701246266315,...,Bread And Cakes>Rye Breads>Other Rye Breads,3.000000,3.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False
1178,d9e869ab-c63c-4218-9932-321d470b7428_571258035...,d9e869ab-c63c-4218-9932-321d470b7428,føtex Eternitten,foetex,Aalborg,57.0375,9.93532,Synergivej 5,9000,5712872146933,...,Bread And Cakes>Rye Breads>Other Rye Breads,4.000000,4.000000,2026-04-01 21:00:01,2026-04-02 23:30:02,0.0,26.500278,80,True,False

In [ ]:
highest_sell_thorugh = df[df['sell_through_rate'] > 0].sort_values(by='sell_through_rate', ascending=False)

highest_sell_thorugh[['store_name', 'product_description', 'offer_percent_discount']]

,store_name,product_description,offer_percent_discount
173,Netto Vesterbro Aalborg,LAMMECULOTTE PREMIEUR,52.47
291,Netto Vestre Allé,FANØ BRØD SIGNATURBRØD,54.14
207,Netto Hadsundvej Aalborg,LF KOLDSKÅL 1% CHEASY,49.39
372,Netto Danmarksgd. Aalborg,SOLSIKKERUGBRØD ØGO,58.97
119,Netto Aalborg,PERSILLE PESTO LA CAMPAGNA,70.62
...,...,...,...
240,Netto Vestre Allé,FÆTTER KRAS REVET THEM,33.33
366,Netto Danmarksgd. Aalborg,SVANEKE SALAMI BORNHOLMER,48.00
293,Netto Vestre Allé,DET GODE SOL RUGBRØD SCHULSTAD,40.74
436,føtex Aalborg,KALKUNBRYST SALLING,30.36
232,Netto Vestre Allé,HØNSESALAT GRAASTEN,20.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   unique_id                  546 non-null    object
 1   store_id                   546 non-null    object
 2   store_name                 546 non-null    object
 3   store_brand                546 non-null    object
 4   store_city                 546 non-null    object
 5   store_lat                  546 non-null    float64
 6   store_lng                  546 non-null    float64
 7   store_street               546 non-null    object
 8   store_zip                  546 non-null    object
 9   product_ean                546 non-null    object
 10  product_description        546 non-null    object
 11  offer_ean                  546 non-null    object
 12  offer_original_price       546 non-null    float64
 13  offer_new_price            546 non-null    float64
 14  offer_discount             546 non-null    float64
 15  offer_percent_discount     546 non-null    float64
 16  offer_stock_unit           546 non-null    object
 17  offer_start_time           546 non-null    datetime64[us]
 18  offer_end_time             546 non-null    datetime64[us]
 19  store_customer_flow_today  546 non-null    object
 20  product_category_da        509 non-null    object
 21  product_category_en        509 non-null    object
 22  initial_stock              546 non-null    float64
 23  final_stock                546 non-null    float64
 24  first_seen                 546 non-null    datetime64[us]
 25  last_seen                  546 non-null    datetime64[us]
 26  sell_through_rate          546 non-null    float64
 27  hours_on_clearance         546 non-null    float64
 28  n_snapshots                546 non-null    int64
 29  had_overnight_gap          546 non-null    bool
 30  potential_relabelling      546 non-null    bool
dtypes: bool(2), datetime64[us](4), float64(10), int64(1), object(14)
memory usage: 124.9+ KB

In [ ]:
# Connect to the MySQL database
conn = get_connection()

# Load the current table into a dataframe
current = pd.read_sql("SELECT * FROM current", conn)

# Load the history table into a dataframe
history = pd.read_sql("SELECT * FROM history", conn)

conn.close()

In [ ]:
current

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,5704000465993,RØGET MEDISTER MEDISTER,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Kødpølse,Dairy And Cold Storage>Lunch Meats>Meat>Meat S...,5712580546964,DKK,29.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.11,0.18,0.24,0.3,0.48,0.58,0.5...","0,0,0,0,0,0,0,0.05,0.12,0.25,0.33,0.52,0.57,0...."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,5709760085764,KYLLINGEPØLSE SALLING ØKO,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Kyllingepålæg,Dairy And Cold Storage>Lunch Meats>Meat>Cold C...,5712580546988,DKK,22.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.11,0.18,0.24,0.3,0.48,0.58,0.5...","0,0,0,0,0,0,0,0.05,0.12,0.25,0.33,0.52,0.57,0...."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,5707196213379,RULLEPØLSE D.G. SLAGTER,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Rullepølse,Dairy And Cold Storage>Lunch Meats>Meat>Sausag...,5712580546995,DKK,16.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.11,0.18,0.24,0.3,0.48,0.58,0.5...","0,0,0,0,0,0,0,0.05,0.12,0.25,0.33,0.52,0.57,0...."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,5712876523761,BAMSEPÅLÆG SALLING,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Kødpølse,Dairy And Cold Storage>Lunch Meats>Meat>Meat S...,5712580547008,DKK,16.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.11,0.18,0.24,0.3,0.48,0.58,0.5...","0,0,0,0,0,0,0,0.05,0.12,0.25,0.33,0.52,0.57,0...."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,5707196372533,ROASTBEEF PÅLÆKKER,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Kødpålæg>Roastbeef,Dairy And Cold Storage>Lunch Meats>Meat>Roastbeef,5712580547015,DKK,20.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,closed,07:00-21:00,"0,0,0,0,0,0,0,0.11,0.18,0.24,0.3,0.48,0.58,0.5...","0,0,0,0,0,0,0,0.05,0.12,0.25,0.33,0.52,0.57,0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5701205009939,FANØ BRØD SIGNATURBRØD,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Rugbrød>Andre rugbrød,Bread And Cakes>Rye Breads>Other Rye Breads,5712580838540,DKK,25.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
357,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258081...,2026-04-03 21:00:02,5701977003067,OAT BARISTA MOC NATURLI',https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Plantebaserede alternative...,Dairy And Cold Storage>Dairy>Plant Based Alter...,5712580816463,DKK,15.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
358,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5704000501950,KYLLING-BACON GRAASTEN,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Pålægssalater>Hønse- & kyll...,Dairy And Cold Storage>Lunch Meats>Mayo Salads...,5712580837642,DKK,10.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
359,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5712877843462,MEDISTER VELSMAG,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Medister,Meat Fish>Pork>Thick Sausages,5712580838830,DKK,35.11,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
360,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5724618720345,ISKAFFE KARAMEL PETER LARSEN,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580837826,DKK,10.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."

In [ ]:
current[['unique_id', 'fetched_at', 'product_description', 'offer_stock', 'store_hours_today']]

,unique_id,fetched_at,product_description,offer_stock,store_hours_today
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,RØGET MEDISTER MEDISTER,3.0,closed
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,KYLLINGEPØLSE SALLING ØKO,4.0,closed
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,RULLEPØLSE D.G. SLAGTER,1.0,closed
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,BAMSEPÅLÆG SALLING,6.0,closed
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-03 21:00:02,ROASTBEEF PÅLÆKKER,8.0,closed
...,...,...,...,...,...
356,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,FANØ BRØD SIGNATURBRØD,2.0,07:00-22:00
357,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258081...,2026-04-03 21:00:02,OAT BARISTA MOC NATURLI',59.0,07:00-22:00
358,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,KYLLING-BACON GRAASTEN,27.0,07:00-22:00
359,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,MEDISTER VELSMAG,3.0,07:00-22:00
360,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,ISKAFFE KARAMEL PETER LARSEN,5.0,07:00-22:00

In [ ]:
sorted_times = current['offer_start_time'].sort_values(ascending=False).unique()

sorted_times

<DatetimeArray>
['2026-04-03 18:40:23', '2026-04-03 18:40:14', '2026-04-03 18:34:10',
 '2026-04-03 18:30:20', '2026-04-03 18:30:04', '2026-04-03 18:27:44',
 '2026-04-03 18:26:32', '2026-04-03 17:51:05', '2026-04-03 17:50:57',
 '2026-04-03 17:50:50',
 ...
 '2026-03-26 15:17:16', '2026-03-26 08:30:45', '2026-03-26 07:46:41',
 '2026-03-25 13:24:26', '2026-03-24 07:59:55', '2026-03-24 07:06:27',
 '2026-03-24 07:06:15', '2026-03-24 07:06:04', '2026-03-20 09:46:10',
 '2026-03-19 18:51:45']
Length: 360, dtype: datetime64[ns]

In [ ]:
current.unique_id

0      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...
1      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...
2      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...
3      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...
4      d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...
                             ...
356    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...
357    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258081...
358    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...
359    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...
360    c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...
Name: unique_id, Length: 361, dtype: object

In [ ]:
current['offer_stock'].value_counts()

offer_stock
1.0      98
2.0      73
3.0      55
4.0      31
5.0      22
6.0      15
10.0     10
7.0      10
8.0       5
9.0       5
11.0      4
12.0      3
22.0      2
17.0      2
13.0      2
25.0      2
14.0      2
37.0      2
18.0      2
27.0      2
88.0      1
40.0      1
74.0      1
33.0      1
110.0     1
53.0      1
32.0      1
35.0      1
24.0      1
42.0      1
57.0      1
29.0      1
43.0      1
59.0      1
Name: count, dtype: int64

In [ ]:
# current['store_brand'] = current['store_brand'].astype('category')

In [ ]:
current.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     361 non-null    object
 1   fetched_at                    361 non-null    datetime64[ns]
 2   product_ean                   361 non-null    object
 3   product_description           361 non-null    object
 4   product_image                 321 non-null    object
 5   product_category_da           311 non-null    object
 6   product_category_en           311 non-null    object
 7   offer_ean                     361 non-null    object
 8   offer_currency                361 non-null    object
 9   offer_original_price          361 non-null    float64
 10  offer_new_price               361 non-null    float64
 11  offer_discount                361 non-null    float64
 12  offer_percent_discount        361 non-null    float64
 13  offer_stock                   361 non-null    float64
 14  offer_stock_unit              361 non-null    object
 15  offer_start_time              361 non-null    datetime64[ns]
 16  offer_end_time                361 non-null    datetime64[ns]
 17  offer_last_update             361 non-null    datetime64[ns]
 18  store_id                      361 non-null    object
 19  store_name                    361 non-null    object
 20  store_brand                   361 non-null    object
 21  store_lat                     361 non-null    float64
 22  store_lng                     361 non-null    float64
 23  store_street                  361 non-null    object
 24  store_city                    361 non-null    object
 25  store_zip                     361 non-null    object
 26  store_country                 361 non-null    object
 27  store_hours_today             361 non-null    object
 28  store_hours_tomorrow          361 non-null    object
 29  store_customer_flow_today     361 non-null    object
 30  store_customer_flow_tomorrow  361 non-null    object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 87.6+ KB

In [ ]:
history

,unique_id,fetched_at,product_ean,product_description,product_image,product_category_da,product_category_en,offer_ean,offer_currency,offer_original_price,...,store_lat,store_lng,store_street,store_city,store_zip,store_country,store_hours_today,store_hours_tomorrow,store_customer_flow_today,store_customer_flow_tomorrow
0,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005225_2...,2026-04-01 18:21:46,250589,NAKKEKOTELET,None,None,None,2005225,DKK,69.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
1,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005195_2...,2026-04-01 18:21:46,250617,STEGEBEN,https://digitalassets.sallinggroup.com/image/u...,None,None,2005195,DKK,59.90,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
2,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005065_2...,2026-04-01 18:21:46,250932,GB URTEKYLLING,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Færdigretter på køl>Middagsretter,Dairy And Cold Storage>Ready To Eat Meals>Dinn...,2005065,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
3,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005089_2...,2026-04-01 18:21:46,252962,KYLLING NUDLER GODT BEGYNDT,https://digitalassets.sallinggroup.com/image/u...,None,None,2005089,DKK,59.95,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
4,d6abf195-312b-4818-8933-bda8ecdd9fbd_2005201_2...,2026-04-01 18:21:46,257809,KOTELETTER,None,None,None,2005201,DKK,65.00,...,57.0473,9.92423,Slotsgade 8-14,Aalborg,9000,DK,07:00-21:00,closed,"0,0,0,0,0,0,0,0.1,0.17,0.2,0.27,0.42,0.45,0.43...","0,0,0,0,0,0,0,0.1,0.18,0.23,0.3,0.45,0.51,0.42..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76726,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5701205009939,FANØ BRØD SIGNATURBRØD,https://digitalassets.sallinggroup.com/image/u...,Brød & kager>Rugbrød>Andre rugbrød,Bread And Cakes>Rye Breads>Other Rye Breads,5712580838540,DKK,25.95,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
76727,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258081...,2026-04-03 21:00:02,5701977003067,OAT BARISTA MOC NATURLI',https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Plantebaserede alternative...,Dairy And Cold Storage>Dairy>Plant Based Alter...,5712580816463,DKK,15.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
76728,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5704000501950,KYLLING-BACON GRAASTEN,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Pålæg>Pålægssalater>Hønse- & kyll...,Dairy And Cold Storage>Lunch Meats>Mayo Salads...,5712580837642,DKK,10.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
76729,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5712877843462,MEDISTER VELSMAG,https://digitalassets.sallinggroup.com/image/u...,Kød & fisk>Grisekød>Medister,Meat Fish>Pork>Thick Sausages,5712580838830,DKK,35.11,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."
76730,c73f2e63-1bd3-43a7-a0b7-b52f380f0e4e_571258083...,2026-04-03 21:00:02,5724618720345,ISKAFFE KARAMEL PETER LARSEN,https://digitalassets.sallinggroup.com/image/u...,Mejeri & køl>Mejeri>Kolde kaffedrikke & kakao,Dairy And Cold Storage>Dairy>Cold Coffee Drink...,5712580837826,DKK,10.00,...,57.0247,9.94331,Kollegievej 2a,Aalborg,9000,DK,07:00-22:00,07:00-22:00,"0,0,0,0,0,0,0,0.2,0.2,0.29,0.26,0.35,0.31,0.36...","0,0,0,0,0,0,0,0.11,0.14,0.19,0.29,0.3,0.29,0.3..."

In [ ]:
offer_id = history['unique_id'].iloc[34]

offer_id_df = history[history['unique_id'] == offer_id]

offer_id_df[['unique_id', 'fetched_at', 'offer_end_time', 'product_description', 'offer_stock', 'store_hours_today']]

,unique_id,fetched_at,offer_end_time,product_description,offer_stock,store_hours_today
34,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:21:46,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,8.0,07:00-21:00
784,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:48:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
1505,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:49:25,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
2226,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 18:51:45,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
2947,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-01 19:00:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,07:00-21:00
...,...,...,...,...,...,...
39178,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 14:15:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
39787,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 14:30:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
40396,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 14:45:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
40974,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 15:00:18,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed
41550,d6abf195-312b-4818-8933-bda8ecdd9fbd_571258054...,2026-04-02 15:15:02,2026-04-06 21:59:59,PØLSEHORNSPØLSE SALLING,5.0,closed

In [ ]:
history['offer_stock'].value_counts()

offer_stock
1.0      20653
2.0      13808
3.0      10850
4.0       6676
5.0       4585
         ...
71.0         1
96.0         1
91.0         1
111.0        1
110.0        1
Name: count, Length: 120, dtype: int64

In [ ]:
history.nunique()

unique_id                       1542
fetched_at                       154
product_ean                      738
product_description              743
product_image                    547
product_category_da              113
product_category_en              113
offer_ean                       1542
offer_currency                     1
offer_original_price             267
offer_new_price                   74
offer_discount                   355
offer_percent_discount           641
offer_stock                      120
offer_stock_unit                   2
offer_start_time                1538
offer_end_time                    48
offer_last_update               1512
store_id                          10
store_name                        10
store_brand                        2
store_lat                         10
store_lng                         10
store_street                      10
store_city                         1
store_zip                          1
store_country                      1
store_hours_today                  5
store_hours_tomorrow               5
store_customer_flow_today         27
store_customer_flow_tomorrow      27
dtype: int64

In [ ]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76731 entries, 0 to 76730
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   unique_id                     76731 non-null  object
 1   fetched_at                    76731 non-null  datetime64[ns]
 2   product_ean                   76731 non-null  object
 3   product_description           76731 non-null  object
 4   product_image                 70736 non-null  object
 5   product_category_da           69569 non-null  object
 6   product_category_en           69569 non-null  object
 7   offer_ean                     76731 non-null  object
 8   offer_currency                76731 non-null  object
 9   offer_original_price          76731 non-null  float64
 10  offer_new_price               76731 non-null  float64
 11  offer_discount                76731 non-null  float64
 12  offer_percent_discount        76731 non-null  float64
 13  offer_stock                   76731 non-null  float64
 14  offer_stock_unit              76731 non-null  object
 15  offer_start_time              76731 non-null  datetime64[ns]
 16  offer_end_time                76731 non-null  datetime64[ns]
 17  offer_last_update             76731 non-null  datetime64[ns]
 18  store_id                      76731 non-null  object
 19  store_name                    76731 non-null  object
 20  store_brand                   76731 non-null  object
 21  store_lat                     76731 non-null  float64
 22  store_lng                     76731 non-null  float64
 23  store_street                  76731 non-null  object
 24  store_city                    76731 non-null  object
 25  store_zip                     76731 non-null  object
 26  store_country                 76731 non-null  object
 27  store_hours_today             76731 non-null  object
 28  store_hours_tomorrow          76731 non-null  object
 29  store_customer_flow_today     76731 non-null  object
 30  store_customer_flow_tomorrow  76731 non-null  object
dtypes: datetime64[ns](4), float64(7), object(20)
memory usage: 18.1+ MB

In [ ]:
history.dtypes

unique_id                               object
fetched_at                      datetime64[ns]
product_ean                             object
product_description                     object
product_image                           object
product_category_da                     object
product_category_en                     object
offer_ean                               object
offer_currency                          object
offer_original_price                   float64
offer_new_price                        float64
offer_discount                         float64
offer_percent_discount                 float64
offer_stock                            float64
offer_stock_unit                        object
offer_start_time                datetime64[ns]
offer_end_time                  datetime64[ns]
offer_last_update               datetime64[ns]
store_id                                object
store_name                              object
store_brand                             object
store_lat                              float64
store_lng                              float64
store_street                            object
store_city                              object
store_zip                               object
store_country                           object
store_hours_today                       object
store_hours_tomorrow                    object
store_customer_flow_today               object
store_customer_flow_tomorrow            object
dtype: object

In [ ]:
# Save data to a static file for testing

# history.to_csv('test_data/test_history.csv', index=False)
# current.to_csv('test_data/test_current.csv', index=False)